//
// Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
//
// On Sun Nov  2 22:10:34 IST 2025
//
//
// Ports:
// Name                         I/O  size props
// add                            O    32
// RDY_add                        O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// add_a                          I    32
// add_b                          I    32
// EN_add                         I     1 unused
//
// Combinational paths from inputs to outputs:
//   (add_a, add_b, EN_add) -> add
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkFpAdder(CLK,
		 RST_N,

		 add_a,
		 add_b,
		 EN_add,
		 add,
		 RDY_add);
  input  CLK;
  input  RST_N;

  // actionvalue method add
  input  [31 : 0] add_a;
  input  [31 : 0] add_b;
  input  EN_add;
  output [31 : 0] add;
  output RDY_add;

  // signals for module outputs
  wire [31 : 0] add;
  wire RDY_add;

  // ports of submodule ks_adder
  wire [32 : 0] ks_adder_add;
  wire [31 : 0] ks_adder_add_a, ks_adder_add_b;
  wire ks_adder_EN_add, ks_adder_add_cin;

  // rule scheduling signals
  wire CAN_FIRE_add, WILL_FIRE_add;

  // remaining internal signals
  wire [30 : 0] IF_ks_adder_add_7_BIT_25_8_THEN_IF_NOT_add_a_B_ETC___d90;
  wire [23 : 0] _theResult___fst__h179,
		_theResult___fst__h217,
		_theResult___snd_fst__h393,
		_theResult___snd_fst__h395,
		ma__h181,
		ma__h223,
		ma__h232,
		mb__h419,
		mb__h428,
		mb_full__h183,
		shifted_out_bits__h225,
		shifted_out_bits__h421,
		shifted_out_mask__h224,
		shifted_out_mask__h420,
		sticky_mask__h228,
		sticky_mask__h424;
  wire [22 : 0] mant_final__h658;
  wire [7 : 0] exp_final__h659,
	       exp_out__h91,
	       i__h268,
	       i__h314,
	       i__h464,
	       i__h510,
	       shift_amt__h182,
	       shift_amt__h214;
  wire add_a_BITS_30_TO_23_ULE_add_b_BITS_30_TO_23___d3,
       guard__h226,
       guard__h422,
       round_bit__h227,
       round_bit__h423,
       round_up__h231,
       round_up__h427,
       round_up_norm__h657,
       sticky__h229,
       sticky__h425,
       x__h308,
       x__h504,
       y__h267,
       y__h463;

  // actionvalue method add
  assign add =
	     { 1'b1,
	       IF_ks_adder_add_7_BIT_25_8_THEN_IF_NOT_add_a_B_ETC___d90 } ;
  assign RDY_add = 1'd1 ;
  assign CAN_FIRE_add = 1'd1 ;
  assign WILL_FIRE_add = EN_add ;

  // submodule ks_adder
  mkKs ks_adder(.CLK(CLK),
		.RST_N(RST_N),
		.add_a(ks_adder_add_a),
		.add_b(ks_adder_add_b),
		.add_cin(ks_adder_add_cin),
		.EN_add(ks_adder_EN_add),
		.add(ks_adder_add),
		.RDY_add());

  // submodule ks_adder
  assign ks_adder_add_a = { 8'b0, _theResult___fst__h179 } ;
  assign ks_adder_add_b = { 8'b0, _theResult___snd_fst__h393 } ;
  assign ks_adder_add_cin = 1'b0 ;
  assign ks_adder_EN_add = EN_add ;

  // remaining internal signals
  assign IF_ks_adder_add_7_BIT_25_8_THEN_IF_NOT_add_a_B_ETC___d90 =
	     ks_adder_add[25] ?
	       { exp_final__h659, mant_final__h658 } :
	       { exp_out__h91, ks_adder_add[23:1] } ;
  assign _theResult___fst__h179 =
	     (!add_a_BITS_30_TO_23_ULE_add_b_BITS_30_TO_23___d3 ||
	      add_b[30:23] <= add_a[30:23]) ?
	       ma__h181 :
	       _theResult___fst__h217 ;
  assign _theResult___fst__h217 =
	     (shift_amt__h214 < 8'd24) ?
	       ((shift_amt__h214 == 8'd0) ? ma__h181 : ma__h232) :
	       24'd0 ;
  assign _theResult___snd_fst__h393 =
	     add_a_BITS_30_TO_23_ULE_add_b_BITS_30_TO_23___d3 ?
	       mb_full__h183 :
	       _theResult___snd_fst__h395 ;
  assign _theResult___snd_fst__h395 =
	     (shift_amt__h182 < 8'd24) ?
	       ((shift_amt__h182 == 8'd0) ? mb_full__h183 : mb__h428) :
	       24'd0 ;
  assign add_a_BITS_30_TO_23_ULE_add_b_BITS_30_TO_23___d3 =
	     add_a[30:23] <= add_b[30:23] ;
  assign exp_final__h659 = exp_out__h91 + 8'd1 ;
  assign exp_out__h91 =
	     (!add_a_BITS_30_TO_23_ULE_add_b_BITS_30_TO_23___d3 ||
	      add_b[30:23] <= add_a[30:23]) ?
	       add_a[30:23] :
	       add_b[30:23] ;
  assign guard__h226 = shifted_out_bits__h225[i__h268[4:0]] ;
  assign guard__h422 = shifted_out_bits__h421[i__h464[4:0]] ;
  assign i__h268 = shift_amt__h214 - 8'd1 ;
  assign i__h314 = shift_amt__h214 - 8'd2 ;
  assign i__h464 = shift_amt__h182 - 8'd1 ;
  assign i__h510 = shift_amt__h182 - 8'd2 ;
  assign ma__h181 = { 1'b1, add_a[22:0] } ;
  assign ma__h223 = ma__h181 >> shift_amt__h214 ;
  assign ma__h232 = ma__h223 + { 23'd0, round_up__h231 } ;
  assign mant_final__h658 =
	     ks_adder_add[24:2] + { 22'd0, round_up_norm__h657 } ;
  assign mb__h419 = mb_full__h183 >> shift_amt__h182 ;
  assign mb__h428 = mb__h419 + { 23'd0, round_up__h427 } ;
  assign mb_full__h183 = { 1'b1, add_b[22:0] } ;
  assign round_bit__h227 =
	     shift_amt__h214 > 8'd1 && shifted_out_bits__h225[i__h314[4:0]] ;
  assign round_bit__h423 =
	     shift_amt__h182 > 8'd1 && shifted_out_bits__h421[i__h510[4:0]] ;
  assign round_up__h231 = guard__h226 & y__h267 ;
  assign round_up__h427 = guard__h422 & y__h463 ;
  assign round_up_norm__h657 = ks_adder_add[1] & ks_adder_add[2] ;
  assign shift_amt__h182 = add_a[30:23] - add_b[30:23] ;
  assign shift_amt__h214 = add_b[30:23] - add_a[30:23] ;
  assign shifted_out_bits__h225 = ma__h181 & shifted_out_mask__h224 ;
  assign shifted_out_bits__h421 = mb_full__h183 & shifted_out_mask__h420 ;
  assign shifted_out_mask__h224 = (24'd1 << shift_amt__h214) - 24'd1 ;
  assign shifted_out_mask__h420 = (24'd1 << shift_amt__h182) - 24'd1 ;
  assign sticky__h229 =
	     (shifted_out_bits__h225 & sticky_mask__h228) != 24'd0 ;
  assign sticky__h425 =
	     (shifted_out_bits__h421 & sticky_mask__h424) != 24'd0 ;
  assign sticky_mask__h228 =
	     (shift_amt__h214 <= 8'd2) ? 24'd0 : (24'd1 << i__h314) - 24'd1 ;
  assign sticky_mask__h424 =
	     (shift_amt__h182 <= 8'd2) ? 24'd0 : (24'd1 << i__h510) - 24'd1 ;
  assign x__h308 = round_bit__h227 | sticky__h229 ;
  assign x__h504 = round_bit__h423 | sticky__h425 ;
  assign y__h267 = x__h308 | ma__h223[0] ;
  assign y__h463 = x__h504 | mb__h419[0] ;
endmodule  // mkFpAdder

