//
// Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
//
// On Sun Nov  2 22:10:33 IST 2025
//
//
// Ports:
// Name                         I/O  size props
// gout                           O     1
// RDY_gout                       O     1 const
// CLK                            I     1 unused
// RST_N                          I     1 unused
// gout_g1                        I     1
// gout_p1                        I     1
// gout_p0                        I     1
//
// Combinational paths from inputs to outputs:
//   (gout_g1, gout_p1, gout_p0) -> gout
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkgg(CLK,
	    RST_N,

	    gout_g1,
	    gout_p1,
	    gout_p0,
	    gout,
	    RDY_gout);
  input  CLK;
  input  RST_N;

  // value method gout
  input  gout_g1;
  input  gout_p1;
  input  gout_p0;
  output gout;
  output RDY_gout;

  // signals for module outputs
  wire RDY_gout, gout;

  // remaining internal signals
  wire y__h34;

  // value method gout
  assign gout = gout_g1 | y__h34 ;
  assign RDY_gout = 1'd1 ;

  // remaining internal signals
  assign y__h34 = gout_p1 & gout_p0 ;
endmodule  // mkgg

