//
// Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
//
// On Sun Nov  2 22:10:33 IST 2025
//
//
// Ports:
// Name                         I/O  size props
// pout                           O     1
// RDY_pout                       O     1 const
// CLK                            I     1 unused
// RST_N                          I     1 unused
// pout_p1                        I     1
// pout_p0                        I     1
//
// Combinational paths from inputs to outputs:
//   (pout_p1, pout_p0) -> pout
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkgp(CLK,
	    RST_N,

	    pout_p1,
	    pout_p0,
	    pout,
	    RDY_pout);
  input  CLK;
  input  RST_N;

  // value method pout
  input  pout_p1;
  input  pout_p0;
  output pout;
  output RDY_pout;

  // signals for module outputs
  wire RDY_pout, pout;

  // value method pout
  assign pout = pout_p1 & pout_p0 ;
  assign RDY_pout = 1'd1 ;
endmodule  // mkgp

