/*
 * Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
 * 
 * On Mon Nov 10 00:28:56 IST 2025
 * 
 */

/* Generation options: */
#ifndef __mkTbViterbiDecoder_h__
#define __mkTbViterbiDecoder_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkViterbiDecoder.h"


/* Class declaration for the mkTbViterbiDecoder module */
class MOD_mkTbViterbiDecoder : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_RegFile<tUInt32,tUInt32> INST_aRegFile;
  MOD_RegFile<tUInt32,tUInt32> INST_bRegFile;
  MOD_RegFile<tUInt32,tUInt32> INST_backTraceBuffer;
  MOD_Reg<tUInt32> INST_dumpAddr;
  MOD_mkViterbiDecoder INST_dut;
  MOD_RegFile<tUInt32,tUInt32> INST_inputRegFile;
  MOD_RegFile<tUInt8,tUInt32> INST_nRegFile;
  MOD_Reg<tUInt32> INST_outFile;
  MOD_Reg<tUInt32> INST_outMaxAddr;
  MOD_Reg<tUInt8> INST_outState;
  MOD_Reg<tUWide> INST_outWrittenMask;
  MOD_RegFile<tUInt32,tUInt32> INST_outputRegFile;
  MOD_Reg<tUInt8> INST_testDone;
  MOD_Reg<tUInt8> INST_testStart;
 
 /* Constructor */
 public:
  MOD_mkTbViterbiDecoder(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
 
 /* Local definitions */
 private:
  tUInt64 DEF_v__h3160;
  tUInt64 DEF_v__h3068;
  tUInt64 DEF_v__h2870;
  tUInt64 DEF_v__h2767;
  tUInt64 DEF_v__h2687;
  tUInt64 DEF_v__h2607;
  tUInt64 DEF_v__h2527;
  tUInt64 DEF_v__h2447;
  tUInt64 DEF_v__h2342;
  tUInt64 DEF_v__h1939;
  tUInt64 DEF_v__h1555;
  tUInt64 DEF_v__h1418;
  tUInt32 DEF_TASK_fopen___d18;
  tUWide DEF_mask__h2909;
  tUInt32 DEF_outFile___d27;
  tUInt32 DEF_y__h2992;
  tUWide DEF_x__h2941;
  tUWide DEF_x__h2919;
 
 /* Rules */
 public:
  void RL_rl_startTest();
  void RL_rl_doneTest();
  void RL_rl_openFile();
  void RL_rl_dump();
  void RL_rl_close();
  void RL_rl_readReq_NM1();
  void RL_rl_readReq_NM2();
  void RL_rl_readReq_A1();
  void RL_rl_readReq_B1();
  void RL_rl_readReq_Input1();
  void RL_rl_writeReq_Output();
  void RL_rl_readReq_BTB1();
  void RL_rl_writeReq_BTB();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTbViterbiDecoder &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkTbViterbiDecoder &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkTbViterbiDecoder &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkTbViterbiDecoder &backing);
};

#endif /* ifndef __mkTbViterbiDecoder_h__ */
