/*
 * Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
 * 
 * On Mon Nov 10 00:28:56 IST 2025
 * 
 */
#include "bluesim_primitives.h"
#include "mkTbViterbiDecoder.h"


/* Literal declarations */
static unsigned int const UWide_literal_1025_h1_arr[] = { 1u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u };
static tUWide const UWide_literal_1025_h1(1025u, UWide_literal_1025_h1_arr);
static unsigned int const UWide_literal_1025_h0_arr[] = { 0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u };
static tUWide const UWide_literal_1025_h0(1025u, UWide_literal_1025_h0_arr);


/* String declarations */
static std::string const __str_literal_11("%08h\n", 5u);
static std::string const __str_literal_1("A.dat", 5u);
static std::string const __str_literal_2("B.dat", 5u);
static std::string const __str_literal_4("N.dat", 5u);
static std::string const __str_literal_19("[TB] Time=%0t: BTBReg_Read_Port: addr=%d, data=%h ",
					  50u);
static std::string const __str_literal_20("[TB] Time=%0t: BTBReg_Write: addr=%d, data=%h ", 46u);
static std::string const __str_literal_6("[TB] Time=%0t: DUT done; starting output.dat dump (max addr %0d)",
					 64u);
static std::string const __str_literal_10("[TB] Time=%0t: Opened output.dat for write", 42u);
static std::string const __str_literal_5("[TB] Time=%0t: Test started", 27u);
static std::string const __str_literal_15("[TB] Time=%0t: aReg_Read_Port_1: addr=%d, data=%h ",
					  50u);
static std::string const __str_literal_16("[TB] Time=%0t: bReg_Read_Port_1: addr=%d, data=%h ",
					  50u);
static std::string const __str_literal_17("[TB] Time=%0t: inputReg_Read_Port_1: addr=%d, data=%h ",
					  54u);
static std::string const __str_literal_13("[TB] Time=%0t: nReg_Read_Port_1: addr=%d, data=%h ",
					  50u);
static std::string const __str_literal_14("[TB] Time=%0t: nReg_Read_Port_2: addr=%d, data=%h ",
					  50u);
static std::string const __str_literal_12("[TB] Time=%0t: output.dat written up to addr %0d", 48u);
static std::string const __str_literal_18("[TB] Time=%0t: outputReg_Write: addr=%d, data=%h ", 49u);
static std::string const __str_literal_9("[TB] cannot open output.dat", 27u);
static std::string const __str_literal_3("input.dat", 9u);
static std::string const __str_literal_7("output.dat", 10u);
static std::string const __str_literal_8("w", 1u);


/* Constructor */
MOD_mkTbViterbiDecoder::MOD_mkTbViterbiDecoder(tSimStateHdl simHdl,
					       char const *name,
					       Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_aRegFile(simHdl, "aRegFile", this, __str_literal_1, 10u, 32u, 0u, 991u, (tUInt8)0u),
    INST_bRegFile(simHdl, "bRegFile", this, __str_literal_2, 10u, 32u, 0u, 960u, (tUInt8)0u),
    INST_backTraceBuffer(simHdl, "backTraceBuffer", this, 10u, 32u, 0u, 1023u),
    INST_dumpAddr(simHdl, "dumpAddr", this, 11u, 0u, (tUInt8)0u),
    INST_dut(simHdl, "dut", this),
    INST_inputRegFile(simHdl, "inputRegFile", this, __str_literal_3, 10u, 32u, 0u, 1023u, (tUInt8)0u),
    INST_nRegFile(simHdl,
		  "nRegFile",
		  this,
		  __str_literal_4,
		  1u,
		  32u,
		  (tUInt8)0u,
		  (tUInt8)1u,
		  (tUInt8)0u),
    INST_outFile(simHdl, "outFile", this, 32u, 0u, (tUInt8)0u),
    INST_outMaxAddr(simHdl, "outMaxAddr", this, 11u, 0u, (tUInt8)0u),
    INST_outState(simHdl, "outState", this, 2u, (tUInt8)0u, (tUInt8)0u),
    INST_outWrittenMask(simHdl, "outWrittenMask", this, 1025u, UWide_literal_1025_h0, (tUInt8)0u),
    INST_outputRegFile(simHdl, "outputRegFile", this, 11u, 32u, 0u, 1024u),
    INST_testDone(simHdl, "testDone", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_testStart(simHdl, "testStart", this, 1u, (tUInt8)0u, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u),
    DEF_v__h3160(12297829382473034410llu),
    DEF_v__h3068(12297829382473034410llu),
    DEF_v__h2870(12297829382473034410llu),
    DEF_v__h2767(12297829382473034410llu),
    DEF_v__h2687(12297829382473034410llu),
    DEF_v__h2607(12297829382473034410llu),
    DEF_v__h2527(12297829382473034410llu),
    DEF_v__h2447(12297829382473034410llu),
    DEF_v__h2342(12297829382473034410llu),
    DEF_v__h1939(12297829382473034410llu),
    DEF_v__h1555(12297829382473034410llu),
    DEF_v__h1418(12297829382473034410llu),
    DEF_TASK_fopen___d18(2863311530u),
    DEF_mask__h2909(1025u),
    DEF_x__h2941(1025u),
    DEF_x__h2919(1025u)
{
  symbol_count = 27u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkTbViterbiDecoder::init_symbols_0()
{
  init_symbol(&symbols[0u], "aRegFile", SYM_MODULE, &INST_aRegFile);
  init_symbol(&symbols[1u], "backTraceBuffer", SYM_MODULE, &INST_backTraceBuffer);
  init_symbol(&symbols[2u], "bRegFile", SYM_MODULE, &INST_bRegFile);
  init_symbol(&symbols[3u], "dumpAddr", SYM_MODULE, &INST_dumpAddr);
  init_symbol(&symbols[4u], "dut", SYM_MODULE, &INST_dut);
  init_symbol(&symbols[5u], "inputRegFile", SYM_MODULE, &INST_inputRegFile);
  init_symbol(&symbols[6u], "nRegFile", SYM_MODULE, &INST_nRegFile);
  init_symbol(&symbols[7u], "outFile", SYM_MODULE, &INST_outFile);
  init_symbol(&symbols[8u], "outMaxAddr", SYM_MODULE, &INST_outMaxAddr);
  init_symbol(&symbols[9u], "outputRegFile", SYM_MODULE, &INST_outputRegFile);
  init_symbol(&symbols[10u], "outState", SYM_MODULE, &INST_outState);
  init_symbol(&symbols[11u], "outWrittenMask", SYM_MODULE, &INST_outWrittenMask);
  init_symbol(&symbols[12u], "RL_rl_close", SYM_RULE);
  init_symbol(&symbols[13u], "RL_rl_doneTest", SYM_RULE);
  init_symbol(&symbols[14u], "RL_rl_dump", SYM_RULE);
  init_symbol(&symbols[15u], "RL_rl_openFile", SYM_RULE);
  init_symbol(&symbols[16u], "RL_rl_readReq_A1", SYM_RULE);
  init_symbol(&symbols[17u], "RL_rl_readReq_B1", SYM_RULE);
  init_symbol(&symbols[18u], "RL_rl_readReq_BTB1", SYM_RULE);
  init_symbol(&symbols[19u], "RL_rl_readReq_Input1", SYM_RULE);
  init_symbol(&symbols[20u], "RL_rl_readReq_NM1", SYM_RULE);
  init_symbol(&symbols[21u], "RL_rl_readReq_NM2", SYM_RULE);
  init_symbol(&symbols[22u], "RL_rl_startTest", SYM_RULE);
  init_symbol(&symbols[23u], "RL_rl_writeReq_BTB", SYM_RULE);
  init_symbol(&symbols[24u], "RL_rl_writeReq_Output", SYM_RULE);
  init_symbol(&symbols[25u], "testDone", SYM_MODULE, &INST_testDone);
  init_symbol(&symbols[26u], "testStart", SYM_MODULE, &INST_testStart);
}


/* Rule actions */

void MOD_mkTbViterbiDecoder::RL_rl_startTest()
{
  INST_dut.METH_start();
  INST_testStart.METH_write((tUInt8)1u);
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h1418 = dollar_time(sim_hdl);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s,64", &__str_literal_5, DEF_v__h1418);
}

void MOD_mkTbViterbiDecoder::RL_rl_doneTest()
{
  DEF_y__h2992 = INST_outMaxAddr.METH_read();
  INST_testDone.METH_write((tUInt8)1u);
  INST_testStart.METH_write((tUInt8)0u);
  INST_outState.METH_write((tUInt8)1u);
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h1555 = dollar_time(sim_hdl);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s,64,11", &__str_literal_6, DEF_v__h1555, DEF_y__h2992);
}

void MOD_mkTbViterbiDecoder::RL_rl_openFile()
{
  tUInt8 DEF_TASK_fopen_8_EQ_0___d19;
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_TASK_fopen___d18 = dollar_fopen("s,s", &__str_literal_7, &__str_literal_8);
  DEF_TASK_fopen_8_EQ_0___d19 = DEF_TASK_fopen___d18 == 0u;
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    if (DEF_TASK_fopen_8_EQ_0___d19)
      dollar_display(sim_hdl, this, "s", &__str_literal_9);
    if (DEF_TASK_fopen_8_EQ_0___d19)
      dollar_finish(sim_hdl, "32", 1u);
  }
  INST_outFile.METH_write(DEF_TASK_fopen___d18);
  INST_dumpAddr.METH_write(0u);
  INST_outState.METH_write((tUInt8)2u);
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h1939 = dollar_time(sim_hdl);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s,64", &__str_literal_10, DEF_v__h1939);
}

void MOD_mkTbViterbiDecoder::RL_rl_dump()
{
  tUInt32 DEF_x__h2194;
  tUInt8 DEF_NOT_dumpAddr_2_ULE_outMaxAddr_6_3___d30;
  tUInt8 DEF_dumpAddr_2_ULE_outMaxAddr_6___d23;
  tUInt8 DEF_dumpAddr_2_ULE_outMaxAddr_6_3_AND_outWrittenMa_ETC___d26;
  tUInt32 DEF_i__h2175;
  tUInt32 DEF_data__h2029;
  DEF_mask__h2909 = INST_outWrittenMask.METH_read();
  DEF_outFile___d27 = INST_outFile.METH_read();
  DEF_i__h2175 = INST_dumpAddr.METH_read();
  DEF_data__h2029 = INST_outputRegFile.METH_sub(DEF_i__h2175);
  DEF_y__h2992 = INST_outMaxAddr.METH_read();
  DEF_dumpAddr_2_ULE_outMaxAddr_6___d23 = DEF_i__h2175 <= DEF_y__h2992;
  DEF_dumpAddr_2_ULE_outMaxAddr_6_3_AND_outWrittenMa_ETC___d26 = DEF_dumpAddr_2_ULE_outMaxAddr_6___d23 && primExtract8(1u,
														       1025u,
														       DEF_mask__h2909,
														       11u,
														       (tUInt32)(DEF_i__h2175),
														       11u,
														       (tUInt32)(DEF_i__h2175));
  DEF_NOT_dumpAddr_2_ULE_outMaxAddr_6_3___d30 = !DEF_dumpAddr_2_ULE_outMaxAddr_6___d23;
  DEF_x__h2194 = 2047u & (DEF_i__h2175 + 1u);
  if (!(PORT_RST_N == (tUInt8)0u))
    if (DEF_dumpAddr_2_ULE_outMaxAddr_6_3_AND_outWrittenMa_ETC___d26)
      dollar_fwrite(sim_hdl, this, "32,s,32", DEF_outFile___d27, &__str_literal_11, DEF_data__h2029);
  if (DEF_dumpAddr_2_ULE_outMaxAddr_6___d23)
    INST_dumpAddr.METH_write(DEF_x__h2194);
  if (DEF_NOT_dumpAddr_2_ULE_outMaxAddr_6_3___d30)
    INST_outState.METH_write((tUInt8)3u);
}

void MOD_mkTbViterbiDecoder::RL_rl_close()
{
  DEF_outFile___d27 = INST_outFile.METH_read();
  DEF_y__h2992 = INST_outMaxAddr.METH_read();
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_fclose("32", DEF_outFile___d27);
  INST_outState.METH_write((tUInt8)0u);
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h2342 = dollar_time(sim_hdl);
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    dollar_display(sim_hdl, this, "s,64,11", &__str_literal_12, DEF_v__h2342, DEF_y__h2992);
    dollar_finish(sim_hdl, "32", 0u);
  }
}

void MOD_mkTbViterbiDecoder::RL_rl_readReq_NM1()
{
  tUInt32 DEF_data__h2413;
  tUInt8 DEF_dut_readReq_NM1___d36;
  tUInt8 DEF_AVMeth_dut_readReq_NM1;
  DEF_AVMeth_dut_readReq_NM1 = INST_dut.METH_readReq_NM1();
  DEF_dut_readReq_NM1___d36 = DEF_AVMeth_dut_readReq_NM1;
  DEF_data__h2413 = INST_nRegFile.METH_sub(DEF_dut_readReq_NM1___d36);
  INST_dut.METH_readResp_NM1(DEF_data__h2413);
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h2447 = dollar_time(sim_hdl);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl,
		   this,
		   "s,64,1,32",
		   &__str_literal_13,
		   DEF_v__h2447,
		   DEF_dut_readReq_NM1___d36,
		   DEF_data__h2413);
}

void MOD_mkTbViterbiDecoder::RL_rl_readReq_NM2()
{
  tUInt32 DEF_data__h2496;
  tUInt8 DEF_dut_readReq_NM2___d42;
  tUInt8 DEF_AVMeth_dut_readReq_NM2;
  DEF_AVMeth_dut_readReq_NM2 = INST_dut.METH_readReq_NM2();
  DEF_dut_readReq_NM2___d42 = DEF_AVMeth_dut_readReq_NM2;
  DEF_data__h2496 = INST_nRegFile.METH_sub(DEF_dut_readReq_NM2___d42);
  INST_dut.METH_readResp_NM2(DEF_data__h2496);
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h2527 = dollar_time(sim_hdl);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl,
		   this,
		   "s,64,1,32",
		   &__str_literal_14,
		   DEF_v__h2527,
		   DEF_dut_readReq_NM2___d42,
		   DEF_data__h2496);
}

void MOD_mkTbViterbiDecoder::RL_rl_readReq_A1()
{
  tUInt32 DEF_data__h2576;
  tUInt32 DEF_dut_readReq_A1___d48;
  tUInt32 DEF_AVMeth_dut_readReq_A1;
  DEF_AVMeth_dut_readReq_A1 = INST_dut.METH_readReq_A1();
  DEF_dut_readReq_A1___d48 = DEF_AVMeth_dut_readReq_A1;
  DEF_data__h2576 = INST_aRegFile.METH_sub(DEF_dut_readReq_A1___d48);
  INST_dut.METH_readResp_A1(DEF_data__h2576);
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h2607 = dollar_time(sim_hdl);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl,
		   this,
		   "s,64,10,32",
		   &__str_literal_15,
		   DEF_v__h2607,
		   DEF_dut_readReq_A1___d48,
		   DEF_data__h2576);
}

void MOD_mkTbViterbiDecoder::RL_rl_readReq_B1()
{
  tUInt32 DEF_data__h2656;
  tUInt32 DEF_dut_readReq_B1___d54;
  tUInt32 DEF_AVMeth_dut_readReq_B1;
  DEF_AVMeth_dut_readReq_B1 = INST_dut.METH_readReq_B1();
  DEF_dut_readReq_B1___d54 = DEF_AVMeth_dut_readReq_B1;
  DEF_data__h2656 = INST_bRegFile.METH_sub(DEF_dut_readReq_B1___d54);
  INST_dut.METH_readResp_B1(DEF_data__h2656);
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h2687 = dollar_time(sim_hdl);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl,
		   this,
		   "s,64,10,32",
		   &__str_literal_16,
		   DEF_v__h2687,
		   DEF_dut_readReq_B1___d54,
		   DEF_data__h2656);
}

void MOD_mkTbViterbiDecoder::RL_rl_readReq_Input1()
{
  tUInt32 DEF_data__h2736;
  tUInt32 DEF_dut_readReq_Input1___d60;
  tUInt32 DEF_AVMeth_dut_readReq_Input1;
  DEF_AVMeth_dut_readReq_Input1 = INST_dut.METH_readReq_Input1();
  DEF_dut_readReq_Input1___d60 = DEF_AVMeth_dut_readReq_Input1;
  DEF_data__h2736 = INST_inputRegFile.METH_sub(DEF_dut_readReq_Input1___d60);
  INST_dut.METH_readResp_Input1(DEF_data__h2736);
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h2767 = dollar_time(sim_hdl);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl,
		   this,
		   "s,64,10,32",
		   &__str_literal_17,
		   DEF_v__h2767,
		   DEF_dut_readReq_Input1___d60,
		   DEF_data__h2736);
}

void MOD_mkTbViterbiDecoder::RL_rl_writeReq_Output()
{
  tUInt8 DEF_NOT_dut_writeReq_Output_4_BITS_42_TO_32_5_ULE__ETC___d71;
  tUInt32 DEF_i__h2828;
  tUInt32 DEF_x__h2829;
  tUInt64 DEF_dut_writeReq_Output___d64;
  tUInt64 DEF_AVMeth_dut_writeReq_Output;
  DEF_mask__h2909 = INST_outWrittenMask.METH_read();
  DEF_y__h2992 = INST_outMaxAddr.METH_read();
  DEF_AVMeth_dut_writeReq_Output = INST_dut.METH_writeReq_Output();
  DEF_dut_writeReq_Output___d64 = DEF_AVMeth_dut_writeReq_Output;
  DEF_x__h2829 = (tUInt32)(DEF_dut_writeReq_Output___d64);
  DEF_i__h2828 = (tUInt32)(DEF_dut_writeReq_Output___d64 >> 32u);
  DEF_NOT_dut_writeReq_Output_4_BITS_42_TO_32_5_ULE__ETC___d71 = !(DEF_i__h2828 <= DEF_y__h2992);
  wop_primShiftLWide(1025u, 1025u, UWide_literal_1025_h1, 11u, (tUInt32)(DEF_i__h2828), DEF_x__h2941);
  wop_or(DEF_mask__h2909, DEF_x__h2941, DEF_x__h2919);
  INST_outputRegFile.METH_upd(DEF_i__h2828, DEF_x__h2829);
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h2870 = dollar_time(sim_hdl);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl,
		   this,
		   "s,64,11,32",
		   &__str_literal_18,
		   DEF_v__h2870,
		   DEF_i__h2828,
		   DEF_x__h2829);
  INST_outWrittenMask.METH_write(DEF_x__h2919);
  if (DEF_NOT_dut_writeReq_Output_4_BITS_42_TO_32_5_ULE__ETC___d71)
    INST_outMaxAddr.METH_write(DEF_i__h2828);
}

void MOD_mkTbViterbiDecoder::RL_rl_readReq_BTB1()
{
  tUInt32 DEF_data__h3037;
  tUInt32 DEF_dut_readReq_BTB1___d75;
  tUInt32 DEF_AVMeth_dut_readReq_BTB1;
  DEF_AVMeth_dut_readReq_BTB1 = INST_dut.METH_readReq_BTB1();
  DEF_dut_readReq_BTB1___d75 = DEF_AVMeth_dut_readReq_BTB1;
  DEF_data__h3037 = INST_backTraceBuffer.METH_sub(DEF_dut_readReq_BTB1___d75);
  INST_dut.METH_readResp_BTB1(DEF_data__h3037);
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h3068 = dollar_time(sim_hdl);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl,
		   this,
		   "s,64,10,32",
		   &__str_literal_19,
		   DEF_v__h3068,
		   DEF_dut_readReq_BTB1___d75,
		   DEF_data__h3037);
}

void MOD_mkTbViterbiDecoder::RL_rl_writeReq_BTB()
{
  tUInt32 DEF_i__h3127;
  tUInt32 DEF_x__h3128;
  tUInt64 DEF_dut_writeReq_BTB___d79;
  tUInt64 DEF_AVMeth_dut_writeReq_BTB;
  DEF_AVMeth_dut_writeReq_BTB = INST_dut.METH_writeReq_BTB();
  DEF_dut_writeReq_BTB___d79 = DEF_AVMeth_dut_writeReq_BTB;
  DEF_x__h3128 = (tUInt32)(DEF_dut_writeReq_BTB___d79);
  DEF_i__h3127 = (tUInt32)(DEF_dut_writeReq_BTB___d79 >> 32u);
  INST_backTraceBuffer.METH_upd(DEF_i__h3127, DEF_x__h3128);
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h3160 = dollar_time(sim_hdl);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl,
		   this,
		   "s,64,10,32",
		   &__str_literal_20,
		   DEF_v__h3160,
		   DEF_i__h3127,
		   DEF_x__h3128);
}


/* Methods */


/* Reset routines */

void MOD_mkTbViterbiDecoder::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_testStart.reset_RST(ARG_rst_in);
  INST_testDone.reset_RST(ARG_rst_in);
  INST_outWrittenMask.reset_RST(ARG_rst_in);
  INST_outState.reset_RST(ARG_rst_in);
  INST_outMaxAddr.reset_RST(ARG_rst_in);
  INST_outFile.reset_RST(ARG_rst_in);
  INST_dut.reset_RST_N(ARG_rst_in);
  INST_dumpAddr.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkTbViterbiDecoder::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkTbViterbiDecoder::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_aRegFile.dump_state(indent + 2u);
  INST_bRegFile.dump_state(indent + 2u);
  INST_backTraceBuffer.dump_state(indent + 2u);
  INST_dumpAddr.dump_state(indent + 2u);
  INST_dut.dump_state(indent + 2u);
  INST_inputRegFile.dump_state(indent + 2u);
  INST_nRegFile.dump_state(indent + 2u);
  INST_outFile.dump_state(indent + 2u);
  INST_outMaxAddr.dump_state(indent + 2u);
  INST_outState.dump_state(indent + 2u);
  INST_outWrittenMask.dump_state(indent + 2u);
  INST_outputRegFile.dump_state(indent + 2u);
  INST_testDone.dump_state(indent + 2u);
  INST_testStart.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkTbViterbiDecoder::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 32u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "TASK_fopen___d18", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "mask__h2909", 1025u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "outFile___d27", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h1418", 64u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h1555", 64u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h1939", 64u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h2342", 64u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h2447", 64u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h2527", 64u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h2607", 64u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h2687", 64u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h2767", 64u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h2870", 64u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h3068", 64u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h3160", 64u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h2919", 1025u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h2941", 1025u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "y__h2992", 11u);
  num = INST_aRegFile.dump_VCD_defs(num);
  num = INST_bRegFile.dump_VCD_defs(num);
  num = INST_backTraceBuffer.dump_VCD_defs(num);
  num = INST_dumpAddr.dump_VCD_defs(num);
  num = INST_inputRegFile.dump_VCD_defs(num);
  num = INST_nRegFile.dump_VCD_defs(num);
  num = INST_outFile.dump_VCD_defs(num);
  num = INST_outMaxAddr.dump_VCD_defs(num);
  num = INST_outState.dump_VCD_defs(num);
  num = INST_outWrittenMask.dump_VCD_defs(num);
  num = INST_outputRegFile.dump_VCD_defs(num);
  num = INST_testDone.dump_VCD_defs(num);
  num = INST_testStart.dump_VCD_defs(num);
  if (levels != 1u)
  {
    unsigned int l = levels == 0u ? 0u : levels - 1u;
    num = INST_dut.dump_VCD_defs(l);
  }
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkTbViterbiDecoder::dump_VCD(tVCDDumpType dt,
				      unsigned int levels,
				      MOD_mkTbViterbiDecoder &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
  if (levels != 1u)
    vcd_submodules(dt, levels - 1u, backing);
}

void MOD_mkTbViterbiDecoder::vcd_defs(tVCDDumpType dt, MOD_mkTbViterbiDecoder &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 1025u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 64u);
    vcd_write_x(sim_hdl, num++, 64u);
    vcd_write_x(sim_hdl, num++, 64u);
    vcd_write_x(sim_hdl, num++, 64u);
    vcd_write_x(sim_hdl, num++, 64u);
    vcd_write_x(sim_hdl, num++, 64u);
    vcd_write_x(sim_hdl, num++, 64u);
    vcd_write_x(sim_hdl, num++, 64u);
    vcd_write_x(sim_hdl, num++, 64u);
    vcd_write_x(sim_hdl, num++, 64u);
    vcd_write_x(sim_hdl, num++, 64u);
    vcd_write_x(sim_hdl, num++, 64u);
    vcd_write_x(sim_hdl, num++, 1025u);
    vcd_write_x(sim_hdl, num++, 1025u);
    vcd_write_x(sim_hdl, num++, 11u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_TASK_fopen___d18) != DEF_TASK_fopen___d18)
      {
	vcd_write_val(sim_hdl, num, DEF_TASK_fopen___d18, 32u);
	backing.DEF_TASK_fopen___d18 = DEF_TASK_fopen___d18;
      }
      ++num;
      if ((backing.DEF_mask__h2909) != DEF_mask__h2909)
      {
	vcd_write_val(sim_hdl, num, DEF_mask__h2909, 1025u);
	backing.DEF_mask__h2909 = DEF_mask__h2909;
      }
      ++num;
      if ((backing.DEF_outFile___d27) != DEF_outFile___d27)
      {
	vcd_write_val(sim_hdl, num, DEF_outFile___d27, 32u);
	backing.DEF_outFile___d27 = DEF_outFile___d27;
      }
      ++num;
      if ((backing.DEF_v__h1418) != DEF_v__h1418)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h1418, 64u);
	backing.DEF_v__h1418 = DEF_v__h1418;
      }
      ++num;
      if ((backing.DEF_v__h1555) != DEF_v__h1555)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h1555, 64u);
	backing.DEF_v__h1555 = DEF_v__h1555;
      }
      ++num;
      if ((backing.DEF_v__h1939) != DEF_v__h1939)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h1939, 64u);
	backing.DEF_v__h1939 = DEF_v__h1939;
      }
      ++num;
      if ((backing.DEF_v__h2342) != DEF_v__h2342)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h2342, 64u);
	backing.DEF_v__h2342 = DEF_v__h2342;
      }
      ++num;
      if ((backing.DEF_v__h2447) != DEF_v__h2447)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h2447, 64u);
	backing.DEF_v__h2447 = DEF_v__h2447;
      }
      ++num;
      if ((backing.DEF_v__h2527) != DEF_v__h2527)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h2527, 64u);
	backing.DEF_v__h2527 = DEF_v__h2527;
      }
      ++num;
      if ((backing.DEF_v__h2607) != DEF_v__h2607)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h2607, 64u);
	backing.DEF_v__h2607 = DEF_v__h2607;
      }
      ++num;
      if ((backing.DEF_v__h2687) != DEF_v__h2687)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h2687, 64u);
	backing.DEF_v__h2687 = DEF_v__h2687;
      }
      ++num;
      if ((backing.DEF_v__h2767) != DEF_v__h2767)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h2767, 64u);
	backing.DEF_v__h2767 = DEF_v__h2767;
      }
      ++num;
      if ((backing.DEF_v__h2870) != DEF_v__h2870)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h2870, 64u);
	backing.DEF_v__h2870 = DEF_v__h2870;
      }
      ++num;
      if ((backing.DEF_v__h3068) != DEF_v__h3068)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h3068, 64u);
	backing.DEF_v__h3068 = DEF_v__h3068;
      }
      ++num;
      if ((backing.DEF_v__h3160) != DEF_v__h3160)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h3160, 64u);
	backing.DEF_v__h3160 = DEF_v__h3160;
      }
      ++num;
      if ((backing.DEF_x__h2919) != DEF_x__h2919)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h2919, 1025u);
	backing.DEF_x__h2919 = DEF_x__h2919;
      }
      ++num;
      if ((backing.DEF_x__h2941) != DEF_x__h2941)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h2941, 1025u);
	backing.DEF_x__h2941 = DEF_x__h2941;
      }
      ++num;
      if ((backing.DEF_y__h2992) != DEF_y__h2992)
      {
	vcd_write_val(sim_hdl, num, DEF_y__h2992, 11u);
	backing.DEF_y__h2992 = DEF_y__h2992;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_TASK_fopen___d18, 32u);
      backing.DEF_TASK_fopen___d18 = DEF_TASK_fopen___d18;
      vcd_write_val(sim_hdl, num++, DEF_mask__h2909, 1025u);
      backing.DEF_mask__h2909 = DEF_mask__h2909;
      vcd_write_val(sim_hdl, num++, DEF_outFile___d27, 32u);
      backing.DEF_outFile___d27 = DEF_outFile___d27;
      vcd_write_val(sim_hdl, num++, DEF_v__h1418, 64u);
      backing.DEF_v__h1418 = DEF_v__h1418;
      vcd_write_val(sim_hdl, num++, DEF_v__h1555, 64u);
      backing.DEF_v__h1555 = DEF_v__h1555;
      vcd_write_val(sim_hdl, num++, DEF_v__h1939, 64u);
      backing.DEF_v__h1939 = DEF_v__h1939;
      vcd_write_val(sim_hdl, num++, DEF_v__h2342, 64u);
      backing.DEF_v__h2342 = DEF_v__h2342;
      vcd_write_val(sim_hdl, num++, DEF_v__h2447, 64u);
      backing.DEF_v__h2447 = DEF_v__h2447;
      vcd_write_val(sim_hdl, num++, DEF_v__h2527, 64u);
      backing.DEF_v__h2527 = DEF_v__h2527;
      vcd_write_val(sim_hdl, num++, DEF_v__h2607, 64u);
      backing.DEF_v__h2607 = DEF_v__h2607;
      vcd_write_val(sim_hdl, num++, DEF_v__h2687, 64u);
      backing.DEF_v__h2687 = DEF_v__h2687;
      vcd_write_val(sim_hdl, num++, DEF_v__h2767, 64u);
      backing.DEF_v__h2767 = DEF_v__h2767;
      vcd_write_val(sim_hdl, num++, DEF_v__h2870, 64u);
      backing.DEF_v__h2870 = DEF_v__h2870;
      vcd_write_val(sim_hdl, num++, DEF_v__h3068, 64u);
      backing.DEF_v__h3068 = DEF_v__h3068;
      vcd_write_val(sim_hdl, num++, DEF_v__h3160, 64u);
      backing.DEF_v__h3160 = DEF_v__h3160;
      vcd_write_val(sim_hdl, num++, DEF_x__h2919, 1025u);
      backing.DEF_x__h2919 = DEF_x__h2919;
      vcd_write_val(sim_hdl, num++, DEF_x__h2941, 1025u);
      backing.DEF_x__h2941 = DEF_x__h2941;
      vcd_write_val(sim_hdl, num++, DEF_y__h2992, 11u);
      backing.DEF_y__h2992 = DEF_y__h2992;
    }
}

void MOD_mkTbViterbiDecoder::vcd_prims(tVCDDumpType dt, MOD_mkTbViterbiDecoder &backing)
{
  INST_aRegFile.dump_VCD(dt, backing.INST_aRegFile);
  INST_bRegFile.dump_VCD(dt, backing.INST_bRegFile);
  INST_backTraceBuffer.dump_VCD(dt, backing.INST_backTraceBuffer);
  INST_dumpAddr.dump_VCD(dt, backing.INST_dumpAddr);
  INST_inputRegFile.dump_VCD(dt, backing.INST_inputRegFile);
  INST_nRegFile.dump_VCD(dt, backing.INST_nRegFile);
  INST_outFile.dump_VCD(dt, backing.INST_outFile);
  INST_outMaxAddr.dump_VCD(dt, backing.INST_outMaxAddr);
  INST_outState.dump_VCD(dt, backing.INST_outState);
  INST_outWrittenMask.dump_VCD(dt, backing.INST_outWrittenMask);
  INST_outputRegFile.dump_VCD(dt, backing.INST_outputRegFile);
  INST_testDone.dump_VCD(dt, backing.INST_testDone);
  INST_testStart.dump_VCD(dt, backing.INST_testStart);
}

void MOD_mkTbViterbiDecoder::vcd_submodules(tVCDDumpType dt,
					    unsigned int levels,
					    MOD_mkTbViterbiDecoder &backing)
{
  INST_dut.dump_VCD(dt, levels, backing.INST_dut);
}
