/*
 * Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
 * 
 * On Mon Nov 10 00:28:56 IST 2025
 * 
 */

/* Generation options: */
#ifndef __mkViterbiDecoder_h__
#define __mkViterbiDecoder_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkFpAdder.h"


/* Class declaration for the mkViterbiDecoder module */
class MOD_mkViterbiDecoder : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt32> INST_aValue;
  MOD_Reg<tUInt32> INST_bValue;
  MOD_Reg<tUInt32> INST_baseAddrVCurr;
  MOD_Reg<tUInt32> INST_baseAddrVPrev;
  MOD_Reg<tUInt8> INST_bestFinalState;
  MOD_Reg<tUInt32> INST_bestMin;
  MOD_Reg<tUInt8> INST_bestMinIdx;
  MOD_Reg<tUInt8> INST_bestPrevState;
  MOD_Reg<tUInt8> INST_currState;
  MOD_Reg<tUInt8> INST_currTraceState;
  MOD_Reg<tUInt32> INST_finalMaxProb;
  MOD_Reg<tUInt32> INST_fpAddResult1;
  MOD_mkFpAdder INST_fpAdder1;
  MOD_Reg<tUInt32> INST_inputIndex;
  MOD_Reg<tUInt32> INST_inputValue;
  MOD_Reg<tUInt8> INST_mIndex;
  MOD_Reg<tUInt32> INST_mValue;
  MOD_Reg<tUInt32> INST_maxInputSeqLength;
  MOD_Reg<tUInt32> INST_maxProb;
  MOD_Reg<tUInt8> INST_minIdx;
  MOD_Reg<tUInt8> INST_nIndex;
  MOD_Reg<tUInt32> INST_nValue;
  MOD_Reg<tUInt32> INST_outputOffset;
  MOD_Reg<tUInt32> INST_outputValue;
  MOD_Reg<tUInt32> INST_prevProb;
  MOD_Reg<tUInt8> INST_prevStateIndex;
  MOD_Fifo<tUInt32> INST_readReqFIFO_A1;
  MOD_Fifo<tUInt32> INST_readReqFIFO_B1;
  MOD_Fifo<tUInt32> INST_readReqFIFO_BTB1;
  MOD_Fifo<tUInt32> INST_readReqFIFO_Input1;
  MOD_Fifo<tUInt8> INST_readReqFIFO_NM1;
  MOD_Fifo<tUInt8> INST_readReqFIFO_NM2;
  MOD_Fifo<tUInt32> INST_readRespFIFO_A1;
  MOD_Fifo<tUInt32> INST_readRespFIFO_B1;
  MOD_Fifo<tUInt32> INST_readRespFIFO_BTB1;
  MOD_Fifo<tUInt32> INST_readRespFIFO_Input1;
  MOD_Fifo<tUInt32> INST_readRespFIFO_NM1;
  MOD_Fifo<tUInt32> INST_readRespFIFO_NM2;
  MOD_Reg<tUInt8> INST_rg_done;
  MOD_Reg<tUInt8> INST_rg_fp_err;
  MOD_Reg<tUInt8> INST_rg_input_err;
  MOD_Reg<tUInt8> INST_rg_start;
  MOD_Reg<tUInt8> INST_snapshotIndex;
  MOD_Reg<tUInt8> INST_stateCount;
  MOD_Reg<tUInt8> INST_stateIndex;
  MOD_Reg<tUInt32> INST_timeStep;
  MOD_Reg<tUInt32> INST_traceBackTime;
  MOD_Reg<tUWide> INST_vCurrSnapshot;
  MOD_Fifo<tUInt64> INST_writeReqFIFO_BTB;
  MOD_Fifo<tUInt64> INST_writeReqFIFO_Output;
 
 /* Constructor */
 public:
  MOD_mkViterbiDecoder(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_rg_start__h5591;
  tUInt8 DEF_rg_done__h20996;
 
 /* Local definitions */
 private:
  tUInt8 DEF_readRespFIFO_Input1_first__9_ULE_mValue_2___d63;
  tUInt32 DEF_readRespFIFO_Input1_first____d59;
  tUInt64 DEF_v__h21012;
  tUInt64 DEF_v__h20766;
  tUInt64 DEF_v__h20523;
  tUInt64 DEF_v__h20255;
  tUInt64 DEF_v__h20110;
  tUInt64 DEF_v__h19884;
  tUInt64 DEF_v__h19753;
  tUInt64 DEF_v__h19538;
  tUInt64 DEF_v__h19427;
  tUInt64 DEF_v__h19188;
  tUInt64 DEF_v__h19058;
  tUInt64 DEF_v__h18861;
  tUInt64 DEF_v__h18732;
  tUInt64 DEF_v__h18623;
  tUInt64 DEF_v__h18485;
  tUInt64 DEF_v__h18419;
  tUInt64 DEF_v__h18375;
  tUInt64 DEF_v__h18197;
  tUInt64 DEF_v__h18040;
  tUInt64 DEF_v__h17993;
  tUInt64 DEF_v__h17732;
  tUInt64 DEF_v__h17669;
  tUInt64 DEF_v__h17412;
  tUInt64 DEF_v__h17349;
  tUInt64 DEF_v__h17124;
  tUInt64 DEF_v__h17021;
  tUInt64 DEF_v__h16979;
  tUInt64 DEF_v__h16712;
  tUInt64 DEF_v__h16614;
  tUInt64 DEF_v__h16303;
  tUInt64 DEF_v__h16056;
  tUInt64 DEF_v__h15993;
  tUInt64 DEF_v__h15884;
  tUInt64 DEF_v__h15687;
  tUInt64 DEF_v__h15427;
  tUInt64 DEF_v__h15252;
  tUInt64 DEF_v__h15054;
  tUInt64 DEF_v__h14956;
  tUInt64 DEF_v__h14689;
  tUInt64 DEF_v__h14591;
  tUInt64 DEF_v__h14280;
  tUInt64 DEF_v__h14033;
  tUInt64 DEF_v__h13970;
  tUInt64 DEF_v__h13719;
  tUInt64 DEF_v__h13655;
  tUInt64 DEF_v__h13558;
  tUInt64 DEF_v__h13495;
  tUInt64 DEF_v__h13272;
  tUInt64 DEF_v__h13209;
  tUInt64 DEF_v__h13064;
  tUInt64 DEF_v__h12867;
  tUInt64 DEF_v__h12772;
  tUInt64 DEF_v__h12575;
  tUInt64 DEF_v__h12509;
  tUInt64 DEF_v__h12416;
  tUInt64 DEF_v__h12339;
  tUInt64 DEF_v__h12297;
  tUInt64 DEF_v__h12206;
  tUInt64 DEF_v__h11991;
  tUInt64 DEF_v__h11928;
  tUInt64 DEF_v__h11857;
  tUInt64 DEF_v__h11660;
  tUInt64 DEF_v__h11513;
  tUInt64 DEF_v__h11442;
  tUInt64 DEF_v__h11353;
  tUInt64 DEF_v__h11287;
  tUInt64 DEF_v__h11192;
  tUInt64 DEF_v__h11016;
  tUInt64 DEF_v__h10819;
  tUInt64 DEF_v__h10752;
  tUInt64 DEF_v__h10654;
  tUInt64 DEF_v__h10442;
  tUInt64 DEF_v__h10379;
  tUInt64 DEF_v__h10144;
  tUInt64 DEF_v__h10041;
  tUInt64 DEF_v__h9999;
  tUInt64 DEF_v__h9717;
  tUInt64 DEF_v__h9619;
  tUInt64 DEF_v__h9039;
  tUInt64 DEF_v__h8934;
  tUInt64 DEF_v__h8682;
  tUInt64 DEF_v__h8619;
  tUInt64 DEF_v__h8570;
  tUInt64 DEF_v__h8430;
  tUInt64 DEF_v__h8233;
  tUInt64 DEF_v__h8067;
  tUInt64 DEF_v__h7870;
  tUInt64 DEF_v__h7804;
  tUInt64 DEF_v__h7684;
  tUInt64 DEF_v__h7642;
  tUInt64 DEF_v__h7377;
  tUInt64 DEF_v__h7314;
  tUInt64 DEF_v__h7087;
  tUInt64 DEF_v__h7021;
  tUInt64 DEF_v__h6750;
  tUInt64 DEF_v__h6645;
  tUInt64 DEF_v__h6391;
  tUInt64 DEF_v__h6328;
  tUInt64 DEF_v__h6073;
  tUInt64 DEF_v__h5862;
  tUInt64 DEF_v__h5619;
  tUInt64 DEF_fpAdder1_add___d121;
  tUInt32 DEF_y__h18531;
  tUInt32 DEF_finalProb__h17309;
  tUInt32 DEF_a__h16903;
  tUInt32 DEF_x__h15975;
  tUInt32 DEF_b__h16904;
  tUInt32 DEF_b__h14881;
  tUInt32 DEF_x__h15970;
  tUInt32 DEF_max_state__h19491;
  tUInt32 DEF_x__h19819;
  tUInt32 DEF_readRespFIFO_B1_first____d108;
  tUInt32 DEF_readRespFIFO_A1_first____d106;
  tUInt32 DEF_x__h21244;
  tUInt32 DEF__read__h5404;
  tUInt32 DEF__read__h5373;
  tUInt32 DEF_x__h19852;
  tUInt32 DEF_x__h20089;
  tUInt32 DEF_x__h20175;
  tUInt8 DEF_x__h18700;
  tUInt8 DEF_curr_state__h19490;
  tUInt8 DEF_x__h17650;
  tUInt8 DEF_x__h15653;
  tUInt8 DEF_x__h17983;
  tUInt32 DEF_finalProb__h16918;
  tUInt32 DEF_max_state_ext__h19494;
  tUInt32 DEF_inputValue_ext__h15923;
  tUInt32 DEF_mValue_ext__h15924;
  tUInt32 DEF_x__h15959;
  tUInt8 DEF_y__h18234;
  tUInt8 DEF_fpAdder1_add_21_BIT_0___d123;
  tUInt8 DEF_readRespFIFO_B1_first__08_BIT_31___d112;
  tUInt8 DEF_readRespFIFO_A1_first__06_BIT_31___d110;
  tUInt8 DEF_readRespFIFO_Input1_first__9_EQ_0x0___d60;
  tUInt8 DEF_readRespFIFO_Input1_first__9_EQ_0xFFFFFFFF___d61;
  tUInt8 DEF_NOT_readRespFIFO_A1_first__06_BIT_31_10___d111;
  tUInt8 DEF_NOT_readRespFIFO_B1_first__08_BIT_31_12___d113;
  tUInt8 DEF_NOT_readRespFIFO_Input1_first__9_ULE_mValue_2_3___d64;
  tUInt8 DEF_NOT_readRespFIFO_Input1_first__9_EQ_0xFFFFFFFF_1___d72;
  tUInt8 DEF_NOT_readRespFIFO_Input1_first__9_EQ_0x0_0___d69;
  tUInt8 DEF_NOT_fpAdder1_add_21_BIT_0_23___d126;
  tUInt32 DEF_prevStateIndex_ext__h13904;
  tUInt32 DEF_y__h17639;
  tUInt32 DEF_curr_state_ext__h17621;
  tUInt32 DEF_y__h15960;
  tUInt8 DEF_stateIndex_1__h10330;
  tUInt32 DEF_x__h20156;
  tUInt32 DEF_addr__h10331;
  tUInt32 DEF_bIndex__h15925;
  tUInt8 DEF_x__h15634;
  tUInt8 DEF_x__h17964;
  tUInt64 DEF_baseAddrVCurr_32_PLUS_0_CONCAT_stateIndex_8_MI_ETC___d137;
 
 /* Rules */
 public:
  void RL_rl_IDLE();
  void RL_rl_START();
  void RL_rl_INIT_GET_NM();
  void RL_rl_DONE_GET_NM();
  void RL_rl_V1_CALC_START();
  void RL_rl_GET_INPUT_V1();
  void RL_rl_INIT_COMPUTE_V1();
  void RL_rl_LOOP_V1_INIT_GET_AB();
  void RL_rl_LOOP_V1_DONE_GET_AB();
  void RL_rl_LOOP_V1_INIT_FP_ADD();
  void RL_rl_LOOP_V1_DONE_FP_ADD();
  void RL_rl_LOOP_V1_NEXT_STATE();
  void RL_rl_V1_CALC_END();
  void RL_rl_SWAP_INIT();
  void RL_rl_SWAP_READ_VCURR();
  void RL_rl_SWAP_WRITE_VPREV();
  void RL_rl_VT_CALC_START();
  void RL_rl_VT_GET_INPUT();
  void RL_rl_VT_INIT_J_LOOP();
  void RL_rl_VT_INIT_I_LOOP();
  void RL_rl_VT_GET_PREV_PROB();
  void RL_rl_VT_READ_VPREV_WAIT();
  void RL_rl_VT_INIT_GET_AB();
  void RL_rl_VT_DONE_GET_AB();
  void RL_rl_VT_INIT_FP_ADD();
  void RL_rl_VT_DONE_FP_ADD();
  void RL_rl_VT_LOOP_I_LOOP();
  void RL_rl_VT_SAVE_STATE();
  void RL_rl_VT_GET_B_AND_ADD();
  void RL_rl_VT_ADD_B_TO_MAX();
  void RL_rl_VT_STORE_RESULT();
  void RL_rl_VT_STORE_BTB();
  void RL_rl_VT_LOOP_J_LOOP();
  void RL_rl_VT_MIN_INIT();
  void RL_rl_VT_MIN_READ();
  void RL_rl_VT_MIN_WAIT();
  void RL_rl_VT_MIN_DONE();
  void RL_rl_TRACEBACK_CALC_START();
  void RL_rl_TRACEBACK_LOOP_START();
  void RL_rl_TRACEBACK_LOOP_EXEC();
  void RL_rl_TRACEBACK_WRITE_FINAL_PROB();
  void RL_rl_WRITE_FF_MARKER();
  void RL_rl_INPUT_ERROR();
  void RL_rl_FP_ERROR();
  void RL_rl_DONE();
 
 /* Methods */
 public:
  void METH_start();
  tUInt8 METH_RDY_start();
  tUInt8 METH_done();
  tUInt8 METH_RDY_done();
  tUInt8 METH_inputError();
  tUInt8 METH_RDY_inputError();
  tUInt8 METH_fpError();
  tUInt8 METH_RDY_fpError();
  tUInt8 METH_readReq_NM1();
  tUInt8 METH_RDY_readReq_NM1();
  void METH_readResp_NM1(tUInt32 ARG_readResp_NM1_resp);
  tUInt8 METH_RDY_readResp_NM1();
  tUInt8 METH_readReq_NM2();
  tUInt8 METH_RDY_readReq_NM2();
  void METH_readResp_NM2(tUInt32 ARG_readResp_NM2_resp);
  tUInt8 METH_RDY_readResp_NM2();
  tUInt32 METH_readReq_A1();
  tUInt8 METH_RDY_readReq_A1();
  void METH_readResp_A1(tUInt32 ARG_readResp_A1_resp);
  tUInt8 METH_RDY_readResp_A1();
  tUInt32 METH_readReq_B1();
  tUInt8 METH_RDY_readReq_B1();
  void METH_readResp_B1(tUInt32 ARG_readResp_B1_resp);
  tUInt8 METH_RDY_readResp_B1();
  tUInt32 METH_readReq_Input1();
  tUInt8 METH_RDY_readReq_Input1();
  void METH_readResp_Input1(tUInt32 ARG_readResp_Input1_resp);
  tUInt8 METH_RDY_readResp_Input1();
  tUInt64 METH_writeReq_Output();
  tUInt8 METH_RDY_writeReq_Output();
  tUInt32 METH_readReq_BTB1();
  tUInt8 METH_RDY_readReq_BTB1();
  void METH_readResp_BTB1(tUInt32 ARG_readResp_BTB1_resp);
  tUInt8 METH_RDY_readResp_BTB1();
  tUInt64 METH_writeReq_BTB();
  tUInt8 METH_RDY_writeReq_BTB();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkViterbiDecoder &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkViterbiDecoder &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkViterbiDecoder &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkViterbiDecoder &backing);
};

#endif /* ifndef __mkViterbiDecoder_h__ */
