/*
 * Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
 * 
 * On Mon Nov 10 00:53:02 IST 2025
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkTbViterbiDecoder.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkTbViterbiDecoder::MODEL_mkTbViterbiDecoder()
{
  mkTbViterbiDecoder_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkTbViterbiDecoder()
{
  MODEL_mkTbViterbiDecoder *model = new MODEL_mkTbViterbiDecoder();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkTbViterbiDecoder &INST_top = *((MOD_mkTbViterbiDecoder *)(instance_ptr));
	 tUInt8 DEF_INST_top_INST_dut_DEF_readReqFIFO_A1_i_notFull____d81;
	 tUInt8 DEF_INST_top_INST_dut_DEF_readRespFIFO_A1_i_notEmpty____d100;
	 tUInt8 DEF_INST_top_INST_dut_DEF_readReqFIFO_B1_i_notFull____d82;
	 tUInt8 DEF_INST_top_INST_dut_DEF_readRespFIFO_B1_i_notEmpty____d101;
	 tUInt8 DEF_INST_top_INST_dut_DEF_readReqFIFO_Input1_i_notFull____d49;
	 tUInt8 DEF_INST_top_INST_dut_DEF_readRespFIFO_Input1_i_notEmpty____d55;
	 tUInt8 DEF_INST_top_INST_dut_DEF_writeReqFIFO_Output_i_notFull____d315;
	 tUInt8 DEF_INST_top_INST_dut_DEF_readReqFIFO_BTB1_i_notFull____d162;
	 tUInt8 DEF_INST_top_INST_dut_DEF_readRespFIFO_BTB1_i_notEmpty____d173;
	 tUInt8 DEF_INST_top_INST_dut_DEF_writeReqFIFO_BTB_i_notFull____d128;
	 tUInt8 DEF_INST_top_INST_dut_DEF_currState__h5598;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_IDLE;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_IDLE;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_START;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_START;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_INIT_GET_NM;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_INIT_GET_NM;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_DONE_GET_NM;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_DONE_GET_NM;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_V1_CALC_START;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_V1_CALC_START;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_GET_INPUT_V1;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_GET_INPUT_V1;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_INIT_COMPUTE_V1;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_INIT_COMPUTE_V1;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_LOOP_V1_INIT_GET_AB;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_LOOP_V1_INIT_GET_AB;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_LOOP_V1_DONE_GET_AB;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_LOOP_V1_DONE_GET_AB;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_LOOP_V1_INIT_FP_ADD;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_LOOP_V1_INIT_FP_ADD;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_LOOP_V1_DONE_FP_ADD;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_LOOP_V1_DONE_FP_ADD;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_LOOP_V1_NEXT_STATE;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_LOOP_V1_NEXT_STATE;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_V1_CALC_END;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_V1_CALC_END;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_SWAP_INIT;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_SWAP_INIT;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_SWAP_READ_VCURR;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_SWAP_READ_VCURR;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_SWAP_WRITE_VPREV;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_SWAP_WRITE_VPREV;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_CALC_START;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_CALC_START;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_GET_INPUT;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_GET_INPUT;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_INIT_J_LOOP;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_INIT_J_LOOP;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_INIT_I_LOOP;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_INIT_I_LOOP;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_GET_PREV_PROB;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_GET_PREV_PROB;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_READ_VPREV_WAIT;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_READ_VPREV_WAIT;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_INIT_GET_AB;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_INIT_GET_AB;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_DONE_GET_AB;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_DONE_GET_AB;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_INIT_FP_ADD;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_INIT_FP_ADD;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_DONE_FP_ADD;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_DONE_FP_ADD;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_LOOP_I_LOOP;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_LOOP_I_LOOP;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_SAVE_STATE;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_SAVE_STATE;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_GET_B_AND_ADD;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_GET_B_AND_ADD;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_ADD_B_TO_MAX;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_ADD_B_TO_MAX;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_STORE_RESULT;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_STORE_RESULT;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_STORE_BTB;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_STORE_BTB;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_LOOP_J_LOOP;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_LOOP_J_LOOP;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_MIN_INIT;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_MIN_INIT;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_MIN_READ;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_MIN_READ;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_MIN_WAIT;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_MIN_WAIT;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_MIN_DONE;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_MIN_DONE;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_TRACEBACK_CALC_START;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_TRACEBACK_CALC_START;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_TRACEBACK_LOOP_START;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_TRACEBACK_LOOP_START;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_TRACEBACK_LOOP_EXEC;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_TRACEBACK_LOOP_EXEC;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_TRACEBACK_WRITE_FINAL_PROB;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_TRACEBACK_WRITE_FINAL_PROB;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_WRITE_FF_MARKER;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_WRITE_FF_MARKER;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_INPUT_ERROR;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_INPUT_ERROR;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_FP_ERROR;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_FP_ERROR;
	 tUInt8 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_DONE;
	 tUInt8 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_DONE;
	 tUInt8 DEF_INST_top_DEF_NOT_testDone___d5;
	 tUInt8 DEF_INST_top_DEF_testStart__h1351;
	 tUInt8 DEF_INST_top_DEF_testDone__h1354;
	 tUInt8 DEF_INST_top_DEF_outState__h1452;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_rl_startTest;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_rl_startTest;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_rl_doneTest;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_rl_doneTest;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_rl_openFile;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_rl_openFile;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_rl_dump;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_rl_dump;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_rl_close;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_rl_close;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_rl_readReq_NM1;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_rl_readReq_NM1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_rl_readReq_NM2;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_rl_readReq_NM2;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_rl_readReq_A1;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_rl_readReq_A1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_rl_readReq_B1;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_rl_readReq_B1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_rl_readReq_Input1;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_rl_readReq_Input1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_rl_writeReq_Output;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_rl_writeReq_Output;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_rl_readReq_BTB1;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_rl_readReq_BTB1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_rl_writeReq_BTB;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_rl_writeReq_BTB;
	 DEF_INST_top_DEF_outState__h1452 = INST_top.INST_outState.METH_read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_rl_close = DEF_INST_top_DEF_outState__h1452 == (tUInt8)3u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_rl_close = DEF_INST_top_DEF_CAN_FIRE_RL_rl_close;
	 DEF_INST_top_DEF_testDone__h1354 = INST_top.INST_testDone.METH_read();
	 DEF_INST_top_DEF_testStart__h1351 = INST_top.INST_testStart.METH_read();
	 DEF_INST_top_DEF_NOT_testDone___d5 = !DEF_INST_top_DEF_testDone__h1354;
	 DEF_INST_top_DEF_CAN_FIRE_RL_rl_doneTest = ((DEF_INST_top_DEF_testStart__h1351 && DEF_INST_top_DEF_NOT_testDone___d5) && INST_top.INST_dut.METH_done()) && DEF_INST_top_DEF_outState__h1452 == (tUInt8)0u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_rl_doneTest = DEF_INST_top_DEF_CAN_FIRE_RL_rl_doneTest;
	 DEF_INST_top_DEF_CAN_FIRE_RL_rl_dump = DEF_INST_top_DEF_outState__h1452 == (tUInt8)2u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_rl_dump = DEF_INST_top_DEF_CAN_FIRE_RL_rl_dump;
	 DEF_INST_top_DEF_CAN_FIRE_RL_rl_openFile = DEF_INST_top_DEF_outState__h1452 == (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_rl_openFile = DEF_INST_top_DEF_CAN_FIRE_RL_rl_openFile;
	 DEF_INST_top_DEF_CAN_FIRE_RL_rl_readReq_A1 = INST_top.INST_dut.METH_RDY_readResp_A1() && INST_top.INST_dut.METH_RDY_readReq_A1();
	 DEF_INST_top_DEF_WILL_FIRE_RL_rl_readReq_A1 = DEF_INST_top_DEF_CAN_FIRE_RL_rl_readReq_A1;
	 DEF_INST_top_DEF_CAN_FIRE_RL_rl_readReq_B1 = INST_top.INST_dut.METH_RDY_readResp_B1() && INST_top.INST_dut.METH_RDY_readReq_B1();
	 DEF_INST_top_DEF_WILL_FIRE_RL_rl_readReq_B1 = DEF_INST_top_DEF_CAN_FIRE_RL_rl_readReq_B1;
	 DEF_INST_top_DEF_CAN_FIRE_RL_rl_readReq_BTB1 = INST_top.INST_dut.METH_RDY_readResp_BTB1() && INST_top.INST_dut.METH_RDY_readReq_BTB1();
	 DEF_INST_top_DEF_WILL_FIRE_RL_rl_readReq_BTB1 = DEF_INST_top_DEF_CAN_FIRE_RL_rl_readReq_BTB1;
	 DEF_INST_top_DEF_CAN_FIRE_RL_rl_readReq_Input1 = INST_top.INST_dut.METH_RDY_readResp_Input1() && INST_top.INST_dut.METH_RDY_readReq_Input1();
	 DEF_INST_top_DEF_WILL_FIRE_RL_rl_readReq_Input1 = DEF_INST_top_DEF_CAN_FIRE_RL_rl_readReq_Input1;
	 DEF_INST_top_DEF_CAN_FIRE_RL_rl_readReq_NM1 = INST_top.INST_dut.METH_RDY_readResp_NM1() && INST_top.INST_dut.METH_RDY_readReq_NM1();
	 DEF_INST_top_DEF_WILL_FIRE_RL_rl_readReq_NM1 = DEF_INST_top_DEF_CAN_FIRE_RL_rl_readReq_NM1;
	 DEF_INST_top_DEF_CAN_FIRE_RL_rl_readReq_NM2 = INST_top.INST_dut.METH_RDY_readResp_NM2() && INST_top.INST_dut.METH_RDY_readReq_NM2();
	 DEF_INST_top_DEF_WILL_FIRE_RL_rl_readReq_NM2 = DEF_INST_top_DEF_CAN_FIRE_RL_rl_readReq_NM2;
	 DEF_INST_top_DEF_CAN_FIRE_RL_rl_startTest = INST_top.INST_dut.METH_RDY_start() && (!DEF_INST_top_DEF_testStart__h1351 && DEF_INST_top_DEF_NOT_testDone___d5);
	 DEF_INST_top_DEF_WILL_FIRE_RL_rl_startTest = DEF_INST_top_DEF_CAN_FIRE_RL_rl_startTest;
	 DEF_INST_top_DEF_CAN_FIRE_RL_rl_writeReq_BTB = INST_top.INST_dut.METH_RDY_writeReq_BTB();
	 DEF_INST_top_DEF_WILL_FIRE_RL_rl_writeReq_BTB = DEF_INST_top_DEF_CAN_FIRE_RL_rl_writeReq_BTB;
	 DEF_INST_top_DEF_CAN_FIRE_RL_rl_writeReq_Output = INST_top.INST_dut.METH_RDY_writeReq_Output();
	 DEF_INST_top_DEF_WILL_FIRE_RL_rl_writeReq_Output = DEF_INST_top_DEF_CAN_FIRE_RL_rl_writeReq_Output;
	 DEF_INST_top_INST_dut_DEF_currState__h5598 = INST_top.INST_dut.INST_currState.METH_read();
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_DONE_GET_NM = (INST_top.INST_dut.INST_readRespFIFO_NM1.METH_i_notEmpty() && INST_top.INST_dut.INST_readRespFIFO_NM2.METH_i_notEmpty()) && DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)3u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_DONE_GET_NM = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_DONE_GET_NM;
	 INST_top.INST_dut.DEF_rg_start__h5591 = INST_top.INST_dut.INST_rg_start.METH_read();
	 DEF_INST_top_INST_dut_DEF_writeReqFIFO_Output_i_notFull____d315 = INST_top.INST_dut.INST_writeReqFIFO_Output.METH_i_notFull();
	 INST_top.INST_dut.DEF_rg_done__h20996 = INST_top.INST_dut.INST_rg_done.METH_read();
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_DONE = DEF_INST_top_INST_dut_DEF_writeReqFIFO_Output_i_notFull____d315 && ((DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)45u && INST_top.INST_dut.DEF_rg_start__h5591) && !(INST_top.INST_dut.DEF_rg_done__h20996));
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_DONE = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_DONE;
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_FP_ERROR = DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)47u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_FP_ERROR = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_FP_ERROR;
	 DEF_INST_top_INST_dut_DEF_readRespFIFO_Input1_i_notEmpty____d55 = INST_top.INST_dut.INST_readRespFIFO_Input1.METH_i_notEmpty();
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_GET_INPUT_V1 = DEF_INST_top_INST_dut_DEF_readRespFIFO_Input1_i_notEmpty____d55 && DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)5u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_GET_INPUT_V1 = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_GET_INPUT_V1;
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_IDLE = INST_top.INST_dut.DEF_rg_start__h5591 && DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)0u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_IDLE = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_IDLE;
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_INIT_COMPUTE_V1 = DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)6u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_INIT_COMPUTE_V1 = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_INIT_COMPUTE_V1;
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_INIT_GET_NM = (INST_top.INST_dut.INST_readReqFIFO_NM1.METH_i_notFull() && INST_top.INST_dut.INST_readReqFIFO_NM2.METH_i_notFull()) && DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)2u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_INIT_GET_NM = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_INIT_GET_NM;
	 DEF_INST_top_INST_dut_DEF_writeReqFIFO_BTB_i_notFull____d128 = INST_top.INST_dut.INST_writeReqFIFO_BTB.METH_i_notFull();
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_LOOP_V1_DONE_FP_ADD = DEF_INST_top_INST_dut_DEF_writeReqFIFO_BTB_i_notFull____d128 && DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)10u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_LOOP_V1_DONE_FP_ADD = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_LOOP_V1_DONE_FP_ADD;
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_INPUT_ERROR = DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)46u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_INPUT_ERROR = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_INPUT_ERROR;
	 DEF_INST_top_INST_dut_DEF_readRespFIFO_B1_i_notEmpty____d101 = INST_top.INST_dut.INST_readRespFIFO_B1.METH_i_notEmpty();
	 DEF_INST_top_INST_dut_DEF_readRespFIFO_A1_i_notEmpty____d100 = INST_top.INST_dut.INST_readRespFIFO_A1.METH_i_notEmpty();
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_LOOP_V1_DONE_GET_AB = (DEF_INST_top_INST_dut_DEF_readRespFIFO_A1_i_notEmpty____d100 && DEF_INST_top_INST_dut_DEF_readRespFIFO_B1_i_notEmpty____d101) && DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)8u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_LOOP_V1_DONE_GET_AB = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_LOOP_V1_DONE_GET_AB;
	 INST_top.INST_dut.INST_fpAdder1.METH_RDY_add();
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_LOOP_V1_INIT_FP_ADD = DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)9u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_LOOP_V1_INIT_FP_ADD = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_LOOP_V1_INIT_FP_ADD;
	 DEF_INST_top_INST_dut_DEF_readReqFIFO_B1_i_notFull____d82 = INST_top.INST_dut.INST_readReqFIFO_B1.METH_i_notFull();
	 DEF_INST_top_INST_dut_DEF_readReqFIFO_A1_i_notFull____d81 = INST_top.INST_dut.INST_readReqFIFO_A1.METH_i_notFull();
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_LOOP_V1_INIT_GET_AB = (DEF_INST_top_INST_dut_DEF_readReqFIFO_A1_i_notFull____d81 && DEF_INST_top_INST_dut_DEF_readReqFIFO_B1_i_notFull____d82) && DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)7u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_LOOP_V1_INIT_GET_AB = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_LOOP_V1_INIT_GET_AB;
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_LOOP_V1_NEXT_STATE = DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)11u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_LOOP_V1_NEXT_STATE = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_LOOP_V1_NEXT_STATE;
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_START = DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)1u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_START = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_START;
	 DEF_INST_top_INST_dut_DEF_readReqFIFO_BTB1_i_notFull____d162 = INST_top.INST_dut.INST_readReqFIFO_BTB1.METH_i_notFull();
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_SWAP_READ_VCURR = DEF_INST_top_INST_dut_DEF_readReqFIFO_BTB1_i_notFull____d162 && DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)38u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_SWAP_READ_VCURR = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_SWAP_READ_VCURR;
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_SWAP_INIT = DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)37u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_SWAP_INIT = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_SWAP_INIT;
	 DEF_INST_top_INST_dut_DEF_readRespFIFO_BTB1_i_notEmpty____d173 = INST_top.INST_dut.INST_readRespFIFO_BTB1.METH_i_notEmpty();
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_SWAP_WRITE_VPREV = (DEF_INST_top_INST_dut_DEF_writeReqFIFO_BTB_i_notFull____d128 && DEF_INST_top_INST_dut_DEF_readRespFIFO_BTB1_i_notEmpty____d173) && DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)39u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_SWAP_WRITE_VPREV = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_SWAP_WRITE_VPREV;
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_TRACEBACK_CALC_START = DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)40u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_TRACEBACK_CALC_START = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_TRACEBACK_CALC_START;
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_TRACEBACK_LOOP_EXEC = DEF_INST_top_INST_dut_DEF_readRespFIFO_BTB1_i_notEmpty____d173 && DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)42u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_TRACEBACK_LOOP_EXEC = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_TRACEBACK_LOOP_EXEC;
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_TRACEBACK_LOOP_START = (DEF_INST_top_INST_dut_DEF_writeReqFIFO_Output_i_notFull____d315 && DEF_INST_top_INST_dut_DEF_readReqFIFO_BTB1_i_notFull____d162) && DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)41u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_TRACEBACK_LOOP_START = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_TRACEBACK_LOOP_START;
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_TRACEBACK_WRITE_FINAL_PROB = DEF_INST_top_INST_dut_DEF_writeReqFIFO_Output_i_notFull____d315 && DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)43u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_TRACEBACK_WRITE_FINAL_PROB = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_TRACEBACK_WRITE_FINAL_PROB;
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_V1_CALC_END = DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)12u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_V1_CALC_END = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_V1_CALC_END;
	 DEF_INST_top_INST_dut_DEF_readReqFIFO_Input1_i_notFull____d49 = INST_top.INST_dut.INST_readReqFIFO_Input1.METH_i_notFull();
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_V1_CALC_START = DEF_INST_top_INST_dut_DEF_readReqFIFO_Input1_i_notFull____d49 && DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)4u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_V1_CALC_START = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_V1_CALC_START;
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_ADD_B_TO_MAX = DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)25u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_ADD_B_TO_MAX = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_ADD_B_TO_MAX;
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_CALC_START = DEF_INST_top_INST_dut_DEF_readReqFIFO_Input1_i_notFull____d49 && DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)13u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_CALC_START = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_CALC_START;
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_DONE_FP_ADD = DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)21u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_DONE_FP_ADD = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_DONE_FP_ADD;
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_DONE_GET_AB = DEF_INST_top_INST_dut_DEF_readRespFIFO_A1_i_notEmpty____d100 && DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)19u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_DONE_GET_AB = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_DONE_GET_AB;
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_GET_B_AND_ADD = DEF_INST_top_INST_dut_DEF_readRespFIFO_B1_i_notEmpty____d101 && DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)24u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_GET_B_AND_ADD = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_GET_B_AND_ADD;
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_GET_INPUT = DEF_INST_top_INST_dut_DEF_readRespFIFO_Input1_i_notEmpty____d55 && DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)14u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_GET_INPUT = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_GET_INPUT;
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_INIT_FP_ADD = DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)20u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_INIT_FP_ADD = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_INIT_FP_ADD;
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_GET_PREV_PROB = DEF_INST_top_INST_dut_DEF_readReqFIFO_BTB1_i_notFull____d162 && DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)17u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_GET_PREV_PROB = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_GET_PREV_PROB;
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_INIT_GET_AB = DEF_INST_top_INST_dut_DEF_readReqFIFO_A1_i_notFull____d81 && DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)18u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_INIT_GET_AB = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_INIT_GET_AB;
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_INIT_I_LOOP = DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)16u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_INIT_I_LOOP = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_INIT_I_LOOP;
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_INIT_J_LOOP = DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)15u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_INIT_J_LOOP = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_INIT_J_LOOP;
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_LOOP_I_LOOP = DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)22u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_LOOP_I_LOOP = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_LOOP_I_LOOP;
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_LOOP_J_LOOP = DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)28u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_LOOP_J_LOOP = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_LOOP_J_LOOP;
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_MIN_INIT = DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)29u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_MIN_INIT = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_MIN_INIT;
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_MIN_DONE = DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)32u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_MIN_DONE = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_MIN_DONE;
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_MIN_READ = DEF_INST_top_INST_dut_DEF_readReqFIFO_BTB1_i_notFull____d162 && DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)30u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_MIN_READ = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_MIN_READ;
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_MIN_WAIT = DEF_INST_top_INST_dut_DEF_readRespFIFO_BTB1_i_notEmpty____d173 && DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)31u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_MIN_WAIT = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_MIN_WAIT;
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_READ_VPREV_WAIT = DEF_INST_top_INST_dut_DEF_readRespFIFO_BTB1_i_notEmpty____d173 && DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)36u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_READ_VPREV_WAIT = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_READ_VPREV_WAIT;
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_SAVE_STATE = DEF_INST_top_INST_dut_DEF_readReqFIFO_B1_i_notFull____d82 && DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)23u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_SAVE_STATE = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_SAVE_STATE;
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_STORE_BTB = DEF_INST_top_INST_dut_DEF_writeReqFIFO_BTB_i_notFull____d128 && DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)27u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_STORE_BTB = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_STORE_BTB;
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_WRITE_FF_MARKER = DEF_INST_top_INST_dut_DEF_writeReqFIFO_Output_i_notFull____d315 && DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)44u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_WRITE_FF_MARKER = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_WRITE_FF_MARKER;
	 DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_STORE_RESULT = DEF_INST_top_INST_dut_DEF_writeReqFIFO_BTB_i_notFull____d128 && DEF_INST_top_INST_dut_DEF_currState__h5598 == (tUInt8)26u;
	 DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_STORE_RESULT = DEF_INST_top_INST_dut_DEF_CAN_FIRE_RL_rl_VT_STORE_RESULT;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_rl_doneTest)
	   INST_top.RL_rl_doneTest();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_rl_startTest)
	   INST_top.RL_rl_startTest();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_rl_close)
	   INST_top.RL_rl_close();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_rl_dump)
	   INST_top.RL_rl_dump();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_rl_openFile)
	   INST_top.RL_rl_openFile();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_rl_readReq_NM1)
	   INST_top.RL_rl_readReq_NM1();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_rl_readReq_NM2)
	   INST_top.RL_rl_readReq_NM2();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_rl_readReq_A1)
	   INST_top.RL_rl_readReq_A1();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_rl_readReq_B1)
	   INST_top.RL_rl_readReq_B1();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_rl_readReq_Input1)
	   INST_top.RL_rl_readReq_Input1();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_rl_writeReq_Output)
	   INST_top.RL_rl_writeReq_Output();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_rl_readReq_BTB1)
	   INST_top.RL_rl_readReq_BTB1();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_rl_writeReq_BTB)
	   INST_top.RL_rl_writeReq_BTB();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_DONE)
	   INST_top.INST_dut.RL_rl_DONE();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_DONE_GET_NM)
	   INST_top.INST_dut.RL_rl_DONE_GET_NM();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_FP_ERROR)
	   INST_top.INST_dut.RL_rl_FP_ERROR();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_GET_INPUT_V1)
	   INST_top.INST_dut.RL_rl_GET_INPUT_V1();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_IDLE)
	   INST_top.INST_dut.RL_rl_IDLE();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_INIT_COMPUTE_V1)
	   INST_top.INST_dut.RL_rl_INIT_COMPUTE_V1();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_INIT_GET_NM)
	   INST_top.INST_dut.RL_rl_INIT_GET_NM();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_LOOP_V1_DONE_FP_ADD)
	   INST_top.INST_dut.RL_rl_LOOP_V1_DONE_FP_ADD();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_INPUT_ERROR)
	   INST_top.INST_dut.RL_rl_INPUT_ERROR();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_LOOP_V1_DONE_GET_AB)
	   INST_top.INST_dut.RL_rl_LOOP_V1_DONE_GET_AB();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_LOOP_V1_INIT_FP_ADD)
	   INST_top.INST_dut.RL_rl_LOOP_V1_INIT_FP_ADD();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_LOOP_V1_INIT_GET_AB)
	   INST_top.INST_dut.RL_rl_LOOP_V1_INIT_GET_AB();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_LOOP_V1_NEXT_STATE)
	   INST_top.INST_dut.RL_rl_LOOP_V1_NEXT_STATE();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_START)
	   INST_top.INST_dut.RL_rl_START();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_SWAP_READ_VCURR)
	   INST_top.INST_dut.RL_rl_SWAP_READ_VCURR();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_SWAP_INIT)
	   INST_top.INST_dut.RL_rl_SWAP_INIT();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_SWAP_WRITE_VPREV)
	   INST_top.INST_dut.RL_rl_SWAP_WRITE_VPREV();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_TRACEBACK_CALC_START)
	   INST_top.INST_dut.RL_rl_TRACEBACK_CALC_START();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_TRACEBACK_LOOP_EXEC)
	   INST_top.INST_dut.RL_rl_TRACEBACK_LOOP_EXEC();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_TRACEBACK_LOOP_START)
	   INST_top.INST_dut.RL_rl_TRACEBACK_LOOP_START();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_TRACEBACK_WRITE_FINAL_PROB)
	   INST_top.INST_dut.RL_rl_TRACEBACK_WRITE_FINAL_PROB();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_V1_CALC_END)
	   INST_top.INST_dut.RL_rl_V1_CALC_END();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_V1_CALC_START)
	   INST_top.INST_dut.RL_rl_V1_CALC_START();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_ADD_B_TO_MAX)
	   INST_top.INST_dut.RL_rl_VT_ADD_B_TO_MAX();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_CALC_START)
	   INST_top.INST_dut.RL_rl_VT_CALC_START();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_DONE_FP_ADD)
	   INST_top.INST_dut.RL_rl_VT_DONE_FP_ADD();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_DONE_GET_AB)
	   INST_top.INST_dut.RL_rl_VT_DONE_GET_AB();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_GET_B_AND_ADD)
	   INST_top.INST_dut.RL_rl_VT_GET_B_AND_ADD();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_GET_INPUT)
	   INST_top.INST_dut.RL_rl_VT_GET_INPUT();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_INIT_FP_ADD)
	   INST_top.INST_dut.RL_rl_VT_INIT_FP_ADD();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_GET_PREV_PROB)
	   INST_top.INST_dut.RL_rl_VT_GET_PREV_PROB();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_INIT_GET_AB)
	   INST_top.INST_dut.RL_rl_VT_INIT_GET_AB();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_INIT_I_LOOP)
	   INST_top.INST_dut.RL_rl_VT_INIT_I_LOOP();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_INIT_J_LOOP)
	   INST_top.INST_dut.RL_rl_VT_INIT_J_LOOP();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_LOOP_I_LOOP)
	   INST_top.INST_dut.RL_rl_VT_LOOP_I_LOOP();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_LOOP_J_LOOP)
	   INST_top.INST_dut.RL_rl_VT_LOOP_J_LOOP();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_MIN_INIT)
	   INST_top.INST_dut.RL_rl_VT_MIN_INIT();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_MIN_DONE)
	   INST_top.INST_dut.RL_rl_VT_MIN_DONE();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_MIN_READ)
	   INST_top.INST_dut.RL_rl_VT_MIN_READ();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_MIN_WAIT)
	   INST_top.INST_dut.RL_rl_VT_MIN_WAIT();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_READ_VPREV_WAIT)
	   INST_top.INST_dut.RL_rl_VT_READ_VPREV_WAIT();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_SAVE_STATE)
	   INST_top.INST_dut.RL_rl_VT_SAVE_STATE();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_STORE_BTB)
	   INST_top.INST_dut.RL_rl_VT_STORE_BTB();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_WRITE_FF_MARKER)
	   INST_top.INST_dut.RL_rl_WRITE_FF_MARKER();
	 if (DEF_INST_top_INST_dut_DEF_WILL_FIRE_RL_rl_VT_STORE_RESULT)
	   INST_top.INST_dut.RL_rl_VT_STORE_RESULT();
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_dut.INST_rg_start.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_rg_done.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_rg_input_err.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_rg_fp_err.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_readReqFIFO_NM1.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_dut.INST_readRespFIFO_NM1.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_dut.INST_readReqFIFO_NM2.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_dut.INST_readRespFIFO_NM2.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_dut.INST_readReqFIFO_A1.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_dut.INST_readRespFIFO_A1.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_dut.INST_readReqFIFO_B1.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_dut.INST_readRespFIFO_B1.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_dut.INST_readReqFIFO_Input1.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_dut.INST_readRespFIFO_Input1.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_dut.INST_writeReqFIFO_Output.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_dut.INST_readReqFIFO_BTB1.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_dut.INST_readRespFIFO_BTB1.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_dut.INST_writeReqFIFO_BTB.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_dut.INST_vCurrSnapshot.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_snapshotIndex.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_currState.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_nIndex.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_mIndex.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_inputIndex.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_outputOffset.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_nValue.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_mValue.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_aValue.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_bValue.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_inputValue.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_outputValue.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_maxInputSeqLength.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_stateIndex.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_stateCount.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_timeStep.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_prevStateIndex.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_maxProb.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_prevProb.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_bestPrevState.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_finalMaxProb.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_bestFinalState.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_traceBackTime.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_currTraceState.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_baseAddrVCurr.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_baseAddrVPrev.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_fpAddResult1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_minIdx.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_bestMin.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_bestMinIdx.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_testStart.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_testDone.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_outWrittenMask.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_outMaxAddr.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_outState.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_outFile.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dumpAddr.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkTbViterbiDecoder::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkTbViterbiDecoder_instance = new MOD_mkTbViterbiDecoder(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkTbViterbiDecoder_instance->INST_dut.INST_readReqFIFO_NM1.set_clk_0)("CLK");
  (mkTbViterbiDecoder_instance->INST_dut.INST_readRespFIFO_NM1.set_clk_0)("CLK");
  (mkTbViterbiDecoder_instance->INST_dut.INST_readReqFIFO_NM2.set_clk_0)("CLK");
  (mkTbViterbiDecoder_instance->INST_dut.INST_readRespFIFO_NM2.set_clk_0)("CLK");
  (mkTbViterbiDecoder_instance->INST_dut.INST_readReqFIFO_A1.set_clk_0)("CLK");
  (mkTbViterbiDecoder_instance->INST_dut.INST_readRespFIFO_A1.set_clk_0)("CLK");
  (mkTbViterbiDecoder_instance->INST_dut.INST_readReqFIFO_B1.set_clk_0)("CLK");
  (mkTbViterbiDecoder_instance->INST_dut.INST_readRespFIFO_B1.set_clk_0)("CLK");
  (mkTbViterbiDecoder_instance->INST_dut.INST_readReqFIFO_Input1.set_clk_0)("CLK");
  (mkTbViterbiDecoder_instance->INST_dut.INST_readRespFIFO_Input1.set_clk_0)("CLK");
  (mkTbViterbiDecoder_instance->INST_dut.INST_writeReqFIFO_Output.set_clk_0)("CLK");
  (mkTbViterbiDecoder_instance->INST_dut.INST_readReqFIFO_BTB1.set_clk_0)("CLK");
  (mkTbViterbiDecoder_instance->INST_dut.INST_readRespFIFO_BTB1.set_clk_0)("CLK");
  (mkTbViterbiDecoder_instance->INST_dut.INST_writeReqFIFO_BTB.set_clk_0)("CLK");
  (mkTbViterbiDecoder_instance->INST_dut.INST_fpAdder1.set_clk_0)("CLK");
  (mkTbViterbiDecoder_instance->INST_dut.set_clk_0)("CLK");
  (mkTbViterbiDecoder_instance->set_clk_0)("CLK");
}
void MODEL_mkTbViterbiDecoder::destroy_model()
{
  delete mkTbViterbiDecoder_instance;
  mkTbViterbiDecoder_instance = NULL;
}
void MODEL_mkTbViterbiDecoder::reset_model(bool asserted)
{
  (mkTbViterbiDecoder_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkTbViterbiDecoder::get_instance()
{
  return mkTbViterbiDecoder_instance;
}

/* Fill in version numbers */
void MODEL_mkTbViterbiDecoder::get_version(char const **name, char const **build)
{
  *name = "2021.12.1";
  *build = "fd501401";
}

/* Get the model creation time */
time_t MODEL_mkTbViterbiDecoder::get_creation_time()
{
  
  /* Sun Nov  9 19:23:02 UTC 2025 */
  return 1762716182llu;
}

/* State dumping function */
void MODEL_mkTbViterbiDecoder::dump_state()
{
  (mkTbViterbiDecoder_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkTbViterbiDecoder & mkTbViterbiDecoder_backing(tSimStateHdl simHdl)
{
  static MOD_mkTbViterbiDecoder *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkTbViterbiDecoder(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkTbViterbiDecoder::dump_VCD_defs()
{
  (mkTbViterbiDecoder_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkTbViterbiDecoder::dump_VCD(tVCDDumpType dt)
{
  (mkTbViterbiDecoder_instance->dump_VCD)(dt,
					  vcd_depth(sim_hdl),
					  mkTbViterbiDecoder_backing(sim_hdl));
}
