//
// Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
//
// On Mon Nov 10 01:06:27 IST 2025
//
//
// Ports:
// Name                         I/O  size props
// add                            O    33
// RDY_add                        O     1 const
// CLK                            I     1 unused
// RST_N                          I     1 unused
// add_a                          I    32
// add_b                          I    32
// EN_add                         I     1 unused
//
// Combinational paths from inputs to outputs:
//   (add_a, add_b) -> add
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkFpAdder(CLK,
		 RST_N,

		 add_a,
		 add_b,
		 EN_add,
		 add,
		 RDY_add);
  input  CLK;
  input  RST_N;

  // actionvalue method add
  input  [31 : 0] add_a;
  input  [31 : 0] add_b;
  input  EN_add;
  output [32 : 0] add;
  output RDY_add;

  // signals for module outputs
  wire [32 : 0] add;
  wire RDY_add;

  // rule scheduling signals
  wire CAN_FIRE_add, WILL_FIRE_add;

  // remaining internal signals
  wire [31 : 0] _0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ETC___d714,
		_0_CONCAT_IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_B_ETC___d900,
		c_vec__h267,
		c_vec__h370,
		c_vec__h454,
		p096_XOR_c_vec54__q7,
		p0__h209,
		p0__h312,
		p0__h396,
		result___1__h162,
		x__h28;
  wire [30 : 0] _255_CONCAT_INV_1_SL_add_a_BIT_30_1_XOR_INV_add_ETC__q6;
  wire [29 : 0] _0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ETC___d712,
		_0_CONCAT_IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_B_ETC___d898,
		_0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add_b__ETC___d307;
  wire [28 : 0] _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d505;
  wire [25 : 0] _0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ETC___d706,
		_0_CONCAT_IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_B_ETC___d892,
		_0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add_b__ETC___d301;
  wire [24 : 0] _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547,
		_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d549,
		_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d498;
  wire [23 : 0] IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737,
		IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d739,
		IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146,
		IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d148,
		_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335,
		_theResult_____4_fst__h2136,
		_theResult_____4_fst__h3795,
		_theResult_____4_fst__h513,
		_theResult_____4_snd_fst__h2172,
		ma___1__h127,
		ma___1__h2138,
		ma___1__h471,
		mant_prenorm__h147,
		mb___1__h129,
		mb___1__h3816,
		mb_full__h473,
		shifted_out_bits__h2140,
		shifted_out_bits__h3819,
		shifted_out_mask__h2139,
		shifted_out_mask__h3818,
		sticky_mask__h2143,
		sticky_mask__h3822;
  wire [22 : 0] INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5;
  wire [21 : 0] _0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ETC___d698,
		_0_CONCAT_IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_B_ETC___d884,
		_0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add_b__ETC___d293;
  wire [20 : 0] _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d489;
  wire [17 : 0] _0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ETC___d690,
		_0_CONCAT_IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_B_ETC___d876,
		_0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add_b__ETC___d285;
  wire [16 : 0] _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d481;
  wire [13 : 0] _0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ETC___d680,
		_0_CONCAT_IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_B_ETC___d866,
		_0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add_b__ETC___d275;
  wire [12 : 0] _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d470;
  wire [9 : 0] _0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ETC___d672,
	       _0_CONCAT_IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_B_ETC___d858,
	       _0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add_b__ETC___d267;
  wire [8 : 0] _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d462;
  wire [7 : 0] IF_INV_exp_out___134_BIT_0_THEN_1_ELSE_0__q9,
	       IF_INV_exp_prenorm50_BIT_0_THEN_1_ELSE_0__q10,
	       IF_INV_y529_THEN_1_ELSE_0__q4,
	       IF_INV_y70_THEN_1_ELSE_0__q3,
	       IF_grs_a___131_BIT_0_XOR_grs_b___133_BIT_0_THE_ETC__q8,
	       INV_add_a_BITS_30_TO_23__q1,
	       INV_add_b_BITS_30_TO_23__q2,
	       exp_final__h55504,
	       exp_out___1__h134,
	       exp_prenorm__h150,
	       exp_prenorm__h42855,
	       i__h16480,
	       i__h16525,
	       i__h16606,
	       i__h29111,
	       shift_amt__h472,
	       shift_amt__h509;
  wire [5 : 0] IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d958,
	       IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d929,
	       add_a_BIT_28_8_XOR_INV_add_b_BITS_30_TO_23_2_B_ETC___d138,
	       add_b_BIT_28_1_XOR_INV_add_a_BITS_30_TO_23_5_B_ETC___d71;
  wire [3 : 0] add_a_BIT_26_4_XOR_INV_add_b_BITS_30_TO_23_2_B_ETC___d137,
	       add_b_BIT_26_7_XOR_INV_add_a_BITS_30_TO_23_5_B_ETC___d70;
  wire [2 : 0] IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d728,
	       _theResult_____3_snd_fst__h42918,
	       _theResult_____4_snd__h2137,
	       _theResult_____4_snd__h3796,
	       _theResult_____4_snd_snd_fst__h16476,
	       _theResult_____4_snd_snd_snd_fst__h16603,
	       grs_a___1__h131,
	       grs_a___1__h2145,
	       grs_b___1__h133,
	       grs_b___1__h3824,
	       grs_result__h138;
  wire IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d720,
       IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d724,
       add_a_BITS_30_TO_23_ULE_add_b_BITS_30_TO_23___d8,
       add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_23_2_B_ETC___d140,
       add_b_BIT_30_4_XOR_INV_add_a_BITS_30_TO_23_5_B_ETC___d73,
       g0__h10281,
       g0__h12134,
       g0__h12148,
       g0__h12162,
       g0__h12449,
       g0__h12757,
       g0__h12771,
       g0__h13058,
       g0__h14367,
       g0__h14418,
       g0__h14691,
       g0__h14986,
       g0__h15037,
       g0__h15339,
       g0__h15634,
       g0__h21793,
       g0__h22858,
       g0__h22872,
       g0__h23159,
       g0__h25012,
       g0__h25026,
       g0__h25040,
       g0__h25327,
       g0__h25635,
       g0__h25649,
       g0__h27259,
       g0__h27310,
       g0__h27583,
       g0__h27878,
       g0__h27929,
       g0__h27958,
       g0__h28231,
       g0__h28526,
       g0__h28577,
       g0__h28850,
       g0__h35545,
       g0__h36610,
       g0__h36624,
       g0__h36911,
       g0__h38764,
       g0__h38778,
       g0__h38792,
       g0__h39079,
       g0__h39387,
       g0__h39401,
       g0__h39688,
       g0__h40866,
       g0__h40999,
       g0__h41050,
       g0__h41323,
       g0__h41618,
       g0__h41669,
       g0__h41971,
       g0__h42266,
       g0__h48199,
       g0__h49264,
       g0__h49278,
       g0__h49565,
       g0__h51418,
       g0__h51432,
       g0__h51446,
       g0__h51733,
       g0__h52041,
       g0__h52055,
       g0__h52342,
       g0__h53651,
       g0__h53702,
       g0__h53975,
       g0__h54270,
       g0__h54321,
       g0__h54623,
       g0__h54918,
       g0__h8915,
       g0__h9980,
       g0__h9994,
       g1__h10279,
       g1__h12132,
       g1__h12146,
       g1__h12160,
       g1__h12447,
       g1__h12755,
       g1__h12769,
       g1__h13056,
       g1__h21791,
       g1__h22856,
       g1__h22870,
       g1__h23157,
       g1__h23951,
       g1__h25010,
       g1__h25024,
       g1__h25038,
       g1__h25325,
       g1__h25633,
       g1__h25647,
       g1__h25934,
       g1__h35543,
       g1__h36608,
       g1__h36622,
       g1__h36909,
       g1__h38762,
       g1__h38776,
       g1__h38790,
       g1__h39077,
       g1__h39385,
       g1__h39399,
       g1__h39686,
       g1__h48197,
       g1__h49262,
       g1__h49276,
       g1__h49563,
       g1__h51416,
       g1__h51430,
       g1__h51444,
       g1__h51731,
       g1__h52039,
       g1__h52053,
       g1__h52340,
       g1__h8913,
       g1__h9978,
       g1__h9992,
       grs_carry__h139,
       guard__h2141,
       guard__h3820,
       p0__h10207,
       p0__h10981,
       p0__h11002,
       p0__h12375,
       p0__h12662,
       p0__h12683,
       p0__h12984,
       p0__h23085,
       p0__h23859,
       p0__h23880,
       p0__h25253,
       p0__h25540,
       p0__h25561,
       p0__h25862,
       p0__h26634,
       p0__h26655,
       p0__h26676,
       p0__h36837,
       p0__h37611,
       p0__h37632,
       p0__h39005,
       p0__h39292,
       p0__h39313,
       p0__h39614,
       p0__h49491,
       p0__h50265,
       p0__h50286,
       p0__h51659,
       p0__h51946,
       p0__h51967,
       p0__h52268,
       p1__h10280,
       p1__h12133,
       p1__h12147,
       p1__h12161,
       p1__h12448,
       p1__h12756,
       p1__h12770,
       p1__h13057,
       p1__h21792,
       p1__h22857,
       p1__h22871,
       p1__h23158,
       p1__h25011,
       p1__h25025,
       p1__h25039,
       p1__h25326,
       p1__h25634,
       p1__h25648,
       p1__h25935,
       p1__h35544,
       p1__h36609,
       p1__h36623,
       p1__h36910,
       p1__h38763,
       p1__h38777,
       p1__h38791,
       p1__h39078,
       p1__h39386,
       p1__h39400,
       p1__h39687,
       p1__h48198,
       p1__h49263,
       p1__h49277,
       p1__h49564,
       p1__h51417,
       p1__h51431,
       p1__h51445,
       p1__h51732,
       p1__h52040,
       p1__h52054,
       p1__h52341,
       p1__h8914,
       p1__h9979,
       p1__h9993,
       round_bit__h2142,
       round_bit__h3821,
       sticky__h2144,
       sticky__h3823,
       x__h1000,
       x__h1058,
       x__h1189,
       x__h1247,
       x__h1378,
       x__h1436,
       x__h1567,
       x__h1625,
       x__h1756,
       x__h1814,
       x__h1945,
       x__h2003,
       x__h2470,
       x__h2528,
       x__h2659,
       x__h2717,
       x__h2848,
       x__h2906,
       x__h29204,
       x__h29390,
       x__h29447,
       x__h29633,
       x__h3037,
       x__h3095,
       x__h3226,
       x__h3284,
       x__h3415,
       x__h3473,
       x__h3604,
       x__h3662,
       x__h58759,
       x__h811,
       x__h869,
       y__h10009,
       y__h1001,
       y__h10135,
       y__h10282,
       y__h10296,
       y__h10422,
       y__h1059,
       y__h1190,
       y__h12135,
       y__h12149,
       y__h12163,
       y__h12177,
       y__h12303,
       y__h12450,
       y__h12464,
       y__h1248,
       y__h12590,
       y__h12758,
       y__h12772,
       y__h12786,
       y__h12912,
       y__h13059,
       y__h13073,
       y__h13199,
       y__h1379,
       y__h14368,
       y__h1437,
       y__h14419,
       y__h14448,
       y__h14559,
       y__h14692,
       y__h14743,
       y__h14854,
       y__h14987,
       y__h15038,
       y__h15067,
       y__h15207,
       y__h15340,
       y__h15391,
       y__h15502,
       y__h15635,
       y__h1568,
       y__h15686,
       y__h15826,
       y__h15959,
       y__h1626,
       y__h1757,
       y__h1815,
       y__h1946,
       y__h2004,
       y__h21794,
       y__h22859,
       y__h22873,
       y__h22887,
       y__h23013,
       y__h23160,
       y__h23174,
       y__h23300,
       y__h23954,
       y__h2471,
       y__h25013,
       y__h25027,
       y__h25041,
       y__h25055,
       y__h25181,
       y__h2529,
       y__h25328,
       y__h25342,
       y__h25468,
       y__h25636,
       y__h25650,
       y__h25664,
       y__h25790,
       y__h25937,
       y__h25951,
       y__h2660,
       y__h27127,
       y__h2718,
       y__h27260,
       y__h27311,
       y__h27340,
       y__h27451,
       y__h27584,
       y__h27635,
       y__h27746,
       y__h27879,
       y__h27930,
       y__h27959,
       y__h28099,
       y__h28232,
       y__h28283,
       y__h28394,
       y__h2849,
       y__h28527,
       y__h28578,
       y__h28718,
       y__h28851,
       y__h2907,
       y__h29205,
       y__h29391,
       y__h29448,
       y__h29634,
       y__h3038,
       y__h3096,
       y__h3227,
       y__h3285,
       y__h3416,
       y__h3474,
       y__h35546,
       y__h3605,
       y__h36611,
       y__h36625,
       y__h3663,
       y__h36639,
       y__h36765,
       y__h36912,
       y__h36926,
       y__h37052,
       y__h38765,
       y__h38779,
       y__h38793,
       y__h38807,
       y__h38933,
       y__h39080,
       y__h39094,
       y__h39220,
       y__h39388,
       y__h39402,
       y__h39416,
       y__h39542,
       y__h39689,
       y__h39703,
       y__h39829,
       y__h40867,
       y__h41000,
       y__h41051,
       y__h41080,
       y__h41191,
       y__h41324,
       y__h41375,
       y__h41486,
       y__h41619,
       y__h41670,
       y__h41699,
       y__h41839,
       y__h41972,
       y__h42023,
       y__h42134,
       y__h42267,
       y__h42318,
       y__h42458,
       y__h42591,
       y__h48200,
       y__h49265,
       y__h49279,
       y__h49293,
       y__h49419,
       y__h49566,
       y__h49580,
       y__h49706,
       y__h51419,
       y__h51433,
       y__h51447,
       y__h51461,
       y__h51587,
       y__h51734,
       y__h51748,
       y__h51874,
       y__h52042,
       y__h52056,
       y__h52070,
       y__h52196,
       y__h52343,
       y__h52357,
       y__h52483,
       y__h53652,
       y__h53703,
       y__h53732,
       y__h53843,
       y__h53976,
       y__h54027,
       y__h54138,
       y__h54271,
       y__h54322,
       y__h54351,
       y__h54491,
       y__h54624,
       y__h54675,
       y__h54786,
       y__h54919,
       y__h54970,
       y__h55110,
       y__h55243,
       y__h56228,
       y__h56417,
       y__h56606,
       y__h56795,
       y__h56984,
       y__h57173,
       y__h57597,
       y__h57786,
       y__h57975,
       y__h58164,
       y__h58353,
       y__h58542,
       y__h812,
       y__h870,
       y__h8916,
       y__h9981,
       y__h9995;

  // actionvalue method add
  assign add = { x__h28, x__h58759 } ;
  assign RDY_add = 1'd1 ;
  assign CAN_FIRE_add = 1'd1 ;
  assign WILL_FIRE_add = EN_add ;

  // remaining internal signals
  assign IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d728 =
	     _0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ETC___d714[24] ?
	       _theResult_____3_snd_fst__h42918 :
	       grs_result__h138 ;
  assign IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737 =
	     mant_prenorm__h147 ^
	     { 23'd0,
	       IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d728[2] &&
	       (IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d728[1] ||
		IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d728[0] ||
		mant_prenorm__h147[0]) } ;
  assign IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d739 =
	     mant_prenorm__h147 &
	     { 23'd0,
	       IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d728[2] &&
	       (IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d728[1] ||
		IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d728[0] ||
		mant_prenorm__h147[0]) } ;
  assign IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d958 =
	     { exp_prenorm__h150[5] ^ y__h58164,
	       exp_prenorm__h150[4] ^ y__h57975,
	       exp_prenorm__h150[3] ^ y__h57786,
	       exp_prenorm__h150[2] ^ y__h57597,
	       exp_prenorm__h150[1] ^ exp_prenorm__h150[0],
	       IF_INV_exp_prenorm50_BIT_0_THEN_1_ELSE_0__q10[0] } ;
  assign IF_INV_exp_out___134_BIT_0_THEN_1_ELSE_0__q9 =
	     (~exp_out___1__h134[0]) ? 8'd1 : 8'd0 ;
  assign IF_INV_exp_prenorm50_BIT_0_THEN_1_ELSE_0__q10 =
	     (~exp_prenorm__h150[0]) ? 8'd1 : 8'd0 ;
  assign IF_INV_y529_THEN_1_ELSE_0__q4 = (~y__h2529) ? 8'd1 : 8'd0 ;
  assign IF_INV_y70_THEN_1_ELSE_0__q3 = (~y__h870) ? 8'd1 : 8'd0 ;
  assign IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146 =
	     ma___1__h127 ^ mb___1__h129 ;
  assign IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d148 =
	     ma___1__h127 & mb___1__h129 ;
  assign IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d720 =
	     x__h29390 ^ y__h29391 ;
  assign IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d724 =
	     x__h29204 ^ y__h29205 ;
  assign IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d929 =
	     { exp_out___1__h134[5] ^ y__h56795,
	       exp_out___1__h134[4] ^ y__h56606,
	       exp_out___1__h134[3] ^ y__h56417,
	       exp_out___1__h134[2] ^ y__h56228,
	       exp_out___1__h134[1] ^ exp_out___1__h134[0],
	       IF_INV_exp_out___134_BIT_0_THEN_1_ELSE_0__q9[0] } ;
  assign IF_grs_a___131_BIT_0_XOR_grs_b___133_BIT_0_THE_ETC__q8 =
	     (grs_a___1__h131[0] ^ grs_b___1__h133[0]) ? 8'd1 : 8'd0 ;
  assign INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5 =
	     ~_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335[23:1] ;
  assign INV_add_a_BITS_30_TO_23__q1 = ~add_a[30:23] ;
  assign INV_add_b_BITS_30_TO_23__q2 = ~add_b[30:23] ;
  assign _0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ETC___d672 =
	     { 6'd0,
	       _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d549[24] |
	       y__h40867,
	       g0__h40866,
	       _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d549[22] |
	       y__h41000,
	       g0__h40999 } ;
  assign _0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ETC___d680 =
	     { _0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ETC___d672,
	       _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d549[20] |
	       y__h41191,
	       g0__h41050,
	       _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d549[18] |
	       y__h41324,
	       g0__h41323 } ;
  assign _0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ETC___d690 =
	     { _0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ETC___d680,
	       _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d549[16] |
	       y__h41486,
	       g0__h35545,
	       _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d549[14] |
	       y__h41619,
	       g0__h41618 } ;
  assign _0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ETC___d698 =
	     { _0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ETC___d690,
	       _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d549[12] |
	       y__h41839,
	       g0__h41669,
	       _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d549[10] |
	       y__h41972,
	       g0__h41971 } ;
  assign _0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ETC___d706 =
	     { _0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ETC___d698,
	       _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d549[8] |
	       y__h42134,
	       g0__h38764,
	       _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d549[6] |
	       y__h42267,
	       g0__h42266 } ;
  assign _0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ETC___d712 =
	     { _0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ETC___d706,
	       _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d549[4] |
	       y__h42458,
	       g0__h39387,
	       _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d549[2] |
	       y__h42591,
	       g0__h39688 } ;
  assign _0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ETC___d714 =
	     p0__h312 ^ c_vec__h370 ;
  assign _0_CONCAT_IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_B_ETC___d858 =
	     { 7'd0,
	       g1__h48197 | y__h48200,
	       IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d739[22] |
	       y__h53652,
	       g0__h53651 } ;
  assign _0_CONCAT_IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_B_ETC___d866 =
	     { _0_CONCAT_IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_B_ETC___d858,
	       IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d739[20] |
	       y__h53843,
	       g0__h53702,
	       IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d739[18] |
	       y__h53976,
	       g0__h53975 } ;
  assign _0_CONCAT_IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_B_ETC___d876 =
	     { _0_CONCAT_IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_B_ETC___d866,
	       IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d739[16] |
	       y__h54138,
	       g0__h48199,
	       IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d739[14] |
	       y__h54271,
	       g0__h54270 } ;
  assign _0_CONCAT_IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_B_ETC___d884 =
	     { _0_CONCAT_IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_B_ETC___d876,
	       IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d739[12] |
	       y__h54491,
	       g0__h54321,
	       IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d739[10] |
	       y__h54624,
	       g0__h54623 } ;
  assign _0_CONCAT_IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_B_ETC___d892 =
	     { _0_CONCAT_IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_B_ETC___d884,
	       IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d739[8] |
	       y__h54786,
	       g0__h51418,
	       IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d739[6] |
	       y__h54919,
	       g0__h54918 } ;
  assign _0_CONCAT_IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_B_ETC___d898 =
	     { _0_CONCAT_IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_B_ETC___d892,
	       IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d739[4] |
	       y__h55110,
	       g0__h52041,
	       IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d739[2] |
	       y__h55243,
	       g0__h52342 } ;
  assign _0_CONCAT_IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_B_ETC___d900 =
	     p0__h209 ^ c_vec__h267 ;
  assign _0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add_b__ETC___d267 =
	     { 7'd0,
	       g1__h8913 | y__h8916,
	       IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d148[22] |
	       y__h14368,
	       g0__h14367 } ;
  assign _0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add_b__ETC___d275 =
	     { _0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add_b__ETC___d267,
	       IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d148[20] |
	       y__h14559,
	       g0__h14418,
	       IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d148[18] |
	       y__h14692,
	       g0__h14691 } ;
  assign _0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add_b__ETC___d285 =
	     { _0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add_b__ETC___d275,
	       IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d148[16] |
	       y__h14854,
	       g0__h8915,
	       IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d148[14] |
	       y__h14987,
	       g0__h14986 } ;
  assign _0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add_b__ETC___d293 =
	     { _0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add_b__ETC___d285,
	       IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d148[12] |
	       y__h15207,
	       g0__h15037,
	       IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d148[10] |
	       y__h15340,
	       g0__h15339 } ;
  assign _0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add_b__ETC___d301 =
	     { _0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add_b__ETC___d293,
	       IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d148[8] |
	       y__h15502,
	       g0__h12134,
	       IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d148[6] |
	       y__h15635,
	       g0__h15634 } ;
  assign _0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add_b__ETC___d307 =
	     { _0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add_b__ETC___d301,
	       IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d148[4] |
	       y__h15826,
	       g0__h12757,
	       IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d148[2] |
	       y__h15959,
	       g0__h13058 } ;
  assign _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547 =
	     p096_XOR_c_vec54__q7[24:0] ^ { 24'd0, grs_carry__h139 } ;
  assign _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d549 =
	     p096_XOR_c_vec54__q7[24:0] & { 24'd0, grs_carry__h139 } ;
  assign _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335 =
	     24'd1 << shift_amt__h472 ;
  assign _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d462 =
	     { y__h27127,
	       y__h27127,
	       y__h27127,
	       y__h27127,
	       y__h27127,
	       y__h27127,
	       y__h27127,
	       y__h27127,
	       _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335[22] |
	       y__h27260 } ;
  assign _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d470 =
	     { _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d462,
	       g0__h27259,
	       _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335[20] |
	       y__h27451,
	       g0__h27310,
	       _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335[18] |
	       y__h27584 } ;
  assign _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d481 =
	     { _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d470,
	       g0__h27583,
	       _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335[16] |
	       y__h27746,
	       g0__h21793,
	       _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335[14] |
	       y__h27879 } ;
  assign _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d489 =
	     { _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d481,
	       g0__h27878,
	       _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335[12] |
	       y__h28099,
	       g0__h27929,
	       _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335[10] |
	       y__h28232 } ;
  assign _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d498 =
	     { _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d489,
	       g0__h28231,
	       _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335[8] |
	       y__h28394,
	       g0__h27958,
	       _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335[6] |
	       y__h28527 } ;
  assign _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d505 =
	     { _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d498,
	       g0__h28526,
	       _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335[4] |
	       y__h28718,
	       g0__h28577,
	       _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335[2] |
	       y__h28851 } ;
  assign _255_CONCAT_INV_1_SL_add_a_BIT_30_1_XOR_INV_add_ETC__q6 =
	     { 8'd255,
	       ~_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335[23:1] } ^
	     { _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d505,
	       g0__h28850,
	       _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335[0] } ;
  assign _theResult_____3_snd_fst__h42918 =
	     { _0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ETC___d714[0],
	       IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d720,
	       IF_grs_a___131_BIT_0_XOR_grs_b___133_BIT_0_THE_ETC__q8[0] |
	       IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d724 } ;
  assign _theResult_____4_fst__h2136 =
	     (shift_amt__h509 == 8'd0) ? ma___1__h471 : ma___1__h2138 ;
  assign _theResult_____4_fst__h3795 =
	     (shift_amt__h472 == 8'd0) ? mb_full__h473 : mb___1__h3816 ;
  assign _theResult_____4_fst__h513 =
	     add_b_BIT_30_4_XOR_INV_add_a_BITS_30_TO_23_5_B_ETC___d73 ?
	       _theResult_____4_fst__h2136 :
	       24'd0 ;
  assign _theResult_____4_snd__h2137 =
	     (shift_amt__h509 == 8'd0) ? 3'b0 : grs_a___1__h2145 ;
  assign _theResult_____4_snd__h3796 =
	     (shift_amt__h472 == 8'd0) ? 3'b0 : grs_b___1__h3824 ;
  assign _theResult_____4_snd_fst__h2172 =
	     add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_23_2_B_ETC___d140 ?
	       _theResult_____4_fst__h3795 :
	       24'd0 ;
  assign _theResult_____4_snd_snd_fst__h16476 =
	     add_b_BIT_30_4_XOR_INV_add_a_BITS_30_TO_23_5_B_ETC___d73 ?
	       _theResult_____4_snd__h2137 :
	       3'b001 ;
  assign _theResult_____4_snd_snd_snd_fst__h16603 =
	     add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_23_2_B_ETC___d140 ?
	       _theResult_____4_snd__h3796 :
	       3'b001 ;
  assign add_a_BITS_30_TO_23_ULE_add_b_BITS_30_TO_23___d8 =
	     add_a[30:23] <= add_b[30:23] ;
  assign add_a_BIT_26_4_XOR_INV_add_b_BITS_30_TO_23_2_B_ETC___d137 =
	     { x__h2848 ^ y__h2849,
	       x__h2659 ^ y__h2660,
	       x__h2470 ^ y__h2471,
	       IF_INV_y529_THEN_1_ELSE_0__q4[0] } ;
  assign add_a_BIT_28_8_XOR_INV_add_b_BITS_30_TO_23_2_B_ETC___d138 =
	     { x__h3226 ^ y__h3227,
	       x__h3037 ^ y__h3038,
	       add_a_BIT_26_4_XOR_INV_add_b_BITS_30_TO_23_2_B_ETC___d137 } ;
  assign add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_23_2_B_ETC___d140 =
	     shift_amt__h472 < 8'd24 ;
  assign add_b_BIT_26_7_XOR_INV_add_a_BITS_30_TO_23_5_B_ETC___d70 =
	     { x__h1189 ^ y__h1190,
	       x__h1000 ^ y__h1001,
	       x__h811 ^ y__h812,
	       IF_INV_y70_THEN_1_ELSE_0__q3[0] } ;
  assign add_b_BIT_28_1_XOR_INV_add_a_BITS_30_TO_23_5_B_ETC___d71 =
	     { x__h1567 ^ y__h1568,
	       x__h1378 ^ y__h1379,
	       add_b_BIT_26_7_XOR_INV_add_a_BITS_30_TO_23_5_B_ETC___d70 } ;
  assign add_b_BIT_30_4_XOR_INV_add_a_BITS_30_TO_23_5_B_ETC___d73 =
	     shift_amt__h509 < 8'd24 ;
  assign c_vec__h267 =
	     { _0_CONCAT_IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_B_ETC___d898,
	       IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d739[0],
	       1'd0 } ;
  assign c_vec__h370 =
	     { _0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ETC___d712,
	       _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d549[0],
	       1'd0 } ;
  assign c_vec__h454 =
	     { _0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add_b__ETC___d307,
	       IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d148[0],
	       1'd0 } ;
  assign exp_final__h55504 =
	     { exp_prenorm__h150[7] ^ y__h58542,
	       exp_prenorm__h150[6] ^ y__h58353,
	       IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d958 } ;
  assign exp_out___1__h134 =
	     (!add_a_BITS_30_TO_23_ULE_add_b_BITS_30_TO_23___d8 ||
	      add_b[30:23] <= add_a[30:23]) ?
	       add_a[30:23] :
	       add_b[30:23] ;
  assign exp_prenorm__h150 =
	     _0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ETC___d714[24] ?
	       exp_prenorm__h42855 :
	       exp_out___1__h134 ;
  assign exp_prenorm__h42855 =
	     { exp_out___1__h134[7] ^ y__h57173,
	       exp_out___1__h134[6] ^ y__h56984,
	       IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d929 } ;
  assign g0__h10281 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d148[17] |
	     y__h10422 ;
  assign g0__h12134 = g1__h12755 | y__h12758 ;
  assign g0__h12148 = g1__h12447 | y__h12450 ;
  assign g0__h12162 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d148[13] |
	     y__h12303 ;
  assign g0__h12449 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d148[9] |
	     y__h12590 ;
  assign g0__h12757 = g1__h13056 | y__h13059 ;
  assign g0__h12771 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d148[5] |
	     y__h12912 ;
  assign g0__h13058 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d148[1] |
	     y__h13199 ;
  assign g0__h14367 = g0__h9994 | y__h14419 ;
  assign g0__h14418 = g0__h9980 | y__h14448 ;
  assign g0__h14691 = g0__h10281 | y__h14743 ;
  assign g0__h14986 = g0__h12162 | y__h15038 ;
  assign g0__h15037 = g0__h12148 | y__h15067 ;
  assign g0__h15339 = g0__h12449 | y__h15391 ;
  assign g0__h15634 = g0__h12771 | y__h15686 ;
  assign g0__h21793 = g1__h23951 | y__h23954 ;
  assign g0__h22858 = g1__h23157 | y__h23160 ;
  assign g0__h22872 =
	     _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335[21] |
	     y__h23013 ;
  assign g0__h23159 =
	     _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335[17] |
	     y__h23300 ;
  assign g0__h25012 = g1__h25633 | y__h25636 ;
  assign g0__h25026 = g1__h25325 | y__h25328 ;
  assign g0__h25040 =
	     _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335[13] |
	     y__h25181 ;
  assign g0__h25327 =
	     _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335[9] |
	     y__h25468 ;
  assign g0__h25635 = g1__h25934 | y__h25937 ;
  assign g0__h25649 =
	     _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335[5] |
	     y__h25790 ;
  assign g0__h27259 = g0__h22872 | y__h27311 ;
  assign g0__h27310 = g0__h22858 | y__h27340 ;
  assign g0__h27583 = g0__h23159 | y__h27635 ;
  assign g0__h27878 = g0__h25040 | y__h27930 ;
  assign g0__h27929 = g0__h25026 | y__h27959 ;
  assign g0__h27958 = g0__h25012 | p0__h26634 ;
  assign g0__h28231 = g0__h25327 | y__h28283 ;
  assign g0__h28526 = g0__h25649 | y__h28578 ;
  assign g0__h28577 = g0__h25635 | p0__h26655 ;
  assign g0__h28850 =
	     _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335[1] |
	     p0__h26676 ;
  assign g0__h35545 = g1__h38762 | y__h38765 ;
  assign g0__h36610 = g1__h36909 | y__h36912 ;
  assign g0__h36624 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d549[21] |
	     y__h36765 ;
  assign g0__h36911 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d549[17] |
	     y__h37052 ;
  assign g0__h38764 = g1__h39385 | y__h39388 ;
  assign g0__h38778 = g1__h39077 | y__h39080 ;
  assign g0__h38792 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d549[13] |
	     y__h38933 ;
  assign g0__h39079 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d549[9] |
	     y__h39220 ;
  assign g0__h39387 = g1__h39686 | y__h39689 ;
  assign g0__h39401 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d549[5] |
	     y__h39542 ;
  assign g0__h39688 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d549[1] |
	     y__h39829 ;
  assign g0__h40866 = g1__h35543 | y__h35546 ;
  assign g0__h40999 = g0__h36624 | y__h41051 ;
  assign g0__h41050 = g0__h36610 | y__h41080 ;
  assign g0__h41323 = g0__h36911 | y__h41375 ;
  assign g0__h41618 = g0__h38792 | y__h41670 ;
  assign g0__h41669 = g0__h38778 | y__h41699 ;
  assign g0__h41971 = g0__h39079 | y__h42023 ;
  assign g0__h42266 = g0__h39401 | y__h42318 ;
  assign g0__h48199 = g1__h51416 | y__h51419 ;
  assign g0__h49264 = g1__h49563 | y__h49566 ;
  assign g0__h49278 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d739[21] |
	     y__h49419 ;
  assign g0__h49565 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d739[17] |
	     y__h49706 ;
  assign g0__h51418 = g1__h52039 | y__h52042 ;
  assign g0__h51432 = g1__h51731 | y__h51734 ;
  assign g0__h51446 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d739[13] |
	     y__h51587 ;
  assign g0__h51733 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d739[9] |
	     y__h51874 ;
  assign g0__h52041 = g1__h52340 | y__h52343 ;
  assign g0__h52055 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d739[5] |
	     y__h52196 ;
  assign g0__h52342 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d739[1] |
	     y__h52483 ;
  assign g0__h53651 = g0__h49278 | y__h53703 ;
  assign g0__h53702 = g0__h49264 | y__h53732 ;
  assign g0__h53975 = g0__h49565 | y__h54027 ;
  assign g0__h54270 = g0__h51446 | y__h54322 ;
  assign g0__h54321 = g0__h51432 | y__h54351 ;
  assign g0__h54623 = g0__h51733 | y__h54675 ;
  assign g0__h54918 = g0__h52055 | y__h54970 ;
  assign g0__h8915 = g1__h12132 | y__h12135 ;
  assign g0__h9980 = g1__h10279 | y__h10282 ;
  assign g0__h9994 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d148[21] |
	     y__h10135 ;
  assign g1__h10279 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d148[19] |
	     y__h10296 ;
  assign g1__h12132 = g1__h12146 | y__h12149 ;
  assign g1__h12146 = g1__h12160 | y__h12163 ;
  assign g1__h12160 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d148[15] |
	     y__h12177 ;
  assign g1__h12447 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d148[11] |
	     y__h12464 ;
  assign g1__h12755 = g1__h12769 | y__h12772 ;
  assign g1__h12769 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d148[7] |
	     y__h12786 ;
  assign g1__h13056 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d148[3] |
	     y__h13073 ;
  assign g1__h21791 = g1__h22856 | y__h22859 ;
  assign g1__h22856 = g1__h22870 | y__h22873 ;
  assign g1__h22870 =
	     _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335[23] |
	     y__h22887 ;
  assign g1__h23157 =
	     _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335[19] |
	     y__h23174 ;
  assign g1__h23951 = g1__h25010 | y__h25013 ;
  assign g1__h25010 = g1__h25024 | y__h25027 ;
  assign g1__h25024 = g1__h25038 | y__h25041 ;
  assign g1__h25038 =
	     _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335[15] |
	     y__h25055 ;
  assign g1__h25325 =
	     _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335[11] |
	     y__h25342 ;
  assign g1__h25633 = g1__h25647 | y__h25650 ;
  assign g1__h25647 =
	     _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335[7] |
	     y__h25664 ;
  assign g1__h25934 =
	     _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335[3] |
	     y__h25951 ;
  assign g1__h35543 = g1__h36608 | y__h36611 ;
  assign g1__h36608 = g1__h36622 | y__h36625 ;
  assign g1__h36622 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d549[23] |
	     y__h36639 ;
  assign g1__h36909 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d549[19] |
	     y__h36926 ;
  assign g1__h38762 = g1__h38776 | y__h38779 ;
  assign g1__h38776 = g1__h38790 | y__h38793 ;
  assign g1__h38790 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d549[15] |
	     y__h38807 ;
  assign g1__h39077 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d549[11] |
	     y__h39094 ;
  assign g1__h39385 = g1__h39399 | y__h39402 ;
  assign g1__h39399 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d549[7] |
	     y__h39416 ;
  assign g1__h39686 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d549[3] |
	     y__h39703 ;
  assign g1__h48197 = g1__h49262 | y__h49265 ;
  assign g1__h49262 = g1__h49276 | y__h49279 ;
  assign g1__h49276 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d739[23] |
	     y__h49293 ;
  assign g1__h49563 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d739[19] |
	     y__h49580 ;
  assign g1__h51416 = g1__h51430 | y__h51433 ;
  assign g1__h51430 = g1__h51444 | y__h51447 ;
  assign g1__h51444 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d739[15] |
	     y__h51461 ;
  assign g1__h51731 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d739[11] |
	     y__h51748 ;
  assign g1__h52039 = g1__h52053 | y__h52056 ;
  assign g1__h52053 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d739[7] |
	     y__h52070 ;
  assign g1__h52340 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d739[3] |
	     y__h52357 ;
  assign g1__h8913 = g1__h9978 | y__h9981 ;
  assign g1__h9978 = g1__h9992 | y__h9995 ;
  assign g1__h9992 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d148[23] |
	     y__h10009 ;
  assign grs_a___1__h131 =
	     (!add_a_BITS_30_TO_23_ULE_add_b_BITS_30_TO_23___d8 ||
	      add_b[30:23] <= add_a[30:23]) ?
	       3'b0 :
	       _theResult_____4_snd_snd_fst__h16476 ;
  assign grs_a___1__h2145 =
	     { guard__h2141, round_bit__h2142, sticky__h2144 } ;
  assign grs_b___1__h133 =
	     add_a_BITS_30_TO_23_ULE_add_b_BITS_30_TO_23___d8 ?
	       3'b0 :
	       _theResult_____4_snd_snd_snd_fst__h16603 ;
  assign grs_b___1__h3824 =
	     { guard__h3820, round_bit__h3821, sticky__h3823 } ;
  assign grs_carry__h139 = x__h29633 | y__h29634 ;
  assign grs_result__h138 =
	     { IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d720,
	       IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d724,
	       IF_grs_a___131_BIT_0_XOR_grs_b___133_BIT_0_THE_ETC__q8[0] } ;
  assign guard__h2141 = shifted_out_bits__h2140[i__h16480[4:0]] ;
  assign guard__h3820 = shifted_out_bits__h3819[i__h16606[4:0]] ;
  assign i__h16480 = shift_amt__h509 - 8'd1 ;
  assign i__h16525 = shift_amt__h509 - 8'd2 ;
  assign i__h16606 = shift_amt__h472 - 8'd1 ;
  assign i__h29111 = shift_amt__h472 - 8'd2 ;
  assign ma___1__h127 =
	     (!add_a_BITS_30_TO_23_ULE_add_b_BITS_30_TO_23___d8 ||
	      add_b[30:23] <= add_a[30:23]) ?
	       ma___1__h471 :
	       _theResult_____4_fst__h513 ;
  assign ma___1__h2138 = ma___1__h471 >> shift_amt__h509 ;
  assign ma___1__h471 = { 1'b1, add_a[22:0] } ;
  assign mant_prenorm__h147 =
	     _0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ETC___d714[24] ?
	       _0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ETC___d714[24:1] :
	       _0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ETC___d714[23:0] ;
  assign mb___1__h129 =
	     add_a_BITS_30_TO_23_ULE_add_b_BITS_30_TO_23___d8 ?
	       mb_full__h473 :
	       _theResult_____4_snd_fst__h2172 ;
  assign mb___1__h3816 = mb_full__h473 >> shift_amt__h472 ;
  assign mb_full__h473 = { 1'b1, add_b[22:0] } ;
  assign p096_XOR_c_vec54__q7 = p0__h396 ^ c_vec__h454 ;
  assign p0__h10207 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[21] &
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[20] ;
  assign p0__h10981 = p1__h10280 & p0__h11002 ;
  assign p0__h11002 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[17] &
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[16] ;
  assign p0__h12375 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[13] &
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[12] ;
  assign p0__h12662 = p1__h12448 & p0__h12683 ;
  assign p0__h12683 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[9] &
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[8] ;
  assign p0__h12984 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[5] &
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[4] ;
  assign p0__h209 =
	     { 8'd0,
	       IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737 } ;
  assign p0__h23085 =
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[20] &
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[19] ;
  assign p0__h23859 = p1__h23158 & p0__h23880 ;
  assign p0__h23880 =
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[16] &
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[15] ;
  assign p0__h25253 =
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[12] &
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[11] ;
  assign p0__h25540 = p1__h25326 & p0__h25561 ;
  assign p0__h25561 =
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[8] &
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[7] ;
  assign p0__h25862 =
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[4] &
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[3] ;
  assign p0__h26634 = p1__h25634 & p0__h26655 ;
  assign p0__h26655 = p1__h25935 & p0__h26676 ;
  assign p0__h26676 =
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[0] &
	     _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335[0] ;
  assign p0__h312 =
	     { 7'd0,
	       _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547 } ;
  assign p0__h36837 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[21] &
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[20] ;
  assign p0__h37611 = p1__h36910 & p0__h37632 ;
  assign p0__h37632 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[17] &
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[16] ;
  assign p0__h39005 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[13] &
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[12] ;
  assign p0__h39292 = p1__h39078 & p0__h39313 ;
  assign p0__h39313 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[9] &
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[8] ;
  assign p0__h396 =
	     { 8'b0,
	       IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146 } ;
  assign p0__h39614 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[5] &
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[4] ;
  assign p0__h49491 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[21] &
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[20] ;
  assign p0__h50265 = p1__h49564 & p0__h50286 ;
  assign p0__h50286 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[17] &
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[16] ;
  assign p0__h51659 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[13] &
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[12] ;
  assign p0__h51946 = p1__h51732 & p0__h51967 ;
  assign p0__h51967 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[9] &
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[8] ;
  assign p0__h52268 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[5] &
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[4] ;
  assign p1__h10280 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[19] &
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[18] ;
  assign p1__h12133 = p1__h12147 & p0__h12662 ;
  assign p1__h12147 = p1__h12161 & p0__h12375 ;
  assign p1__h12161 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[15] &
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[14] ;
  assign p1__h12448 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[11] &
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[10] ;
  assign p1__h12756 = p1__h12770 & p0__h12984 ;
  assign p1__h12770 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[7] &
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[6] ;
  assign p1__h13057 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[3] &
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[2] ;
  assign p1__h21792 = p1__h22857 & p0__h23859 ;
  assign p1__h22857 = p1__h22871 & p0__h23085 ;
  assign p1__h22871 =
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[22] &
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[21] ;
  assign p1__h23158 =
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[18] &
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[17] ;
  assign p1__h25011 = p1__h25025 & p0__h25540 ;
  assign p1__h25025 = p1__h25039 & p0__h25253 ;
  assign p1__h25039 =
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[14] &
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[13] ;
  assign p1__h25326 =
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[10] &
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[9] ;
  assign p1__h25634 = p1__h25648 & p0__h25862 ;
  assign p1__h25648 =
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[6] &
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[5] ;
  assign p1__h25935 =
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[2] &
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[1] ;
  assign p1__h35544 = p1__h36609 & p0__h37611 ;
  assign p1__h36609 = p1__h36623 & p0__h36837 ;
  assign p1__h36623 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[23] &
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[22] ;
  assign p1__h36910 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[19] &
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[18] ;
  assign p1__h38763 = p1__h38777 & p0__h39292 ;
  assign p1__h38777 = p1__h38791 & p0__h39005 ;
  assign p1__h38791 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[15] &
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[14] ;
  assign p1__h39078 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[11] &
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[10] ;
  assign p1__h39386 = p1__h39400 & p0__h39614 ;
  assign p1__h39400 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[7] &
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[6] ;
  assign p1__h39687 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[3] &
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[2] ;
  assign p1__h48198 = p1__h49263 & p0__h50265 ;
  assign p1__h49263 = p1__h49277 & p0__h49491 ;
  assign p1__h49277 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[23] &
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[22] ;
  assign p1__h49564 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[19] &
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[18] ;
  assign p1__h51417 = p1__h51431 & p0__h51946 ;
  assign p1__h51431 = p1__h51445 & p0__h51659 ;
  assign p1__h51445 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[15] &
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[14] ;
  assign p1__h51732 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[11] &
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[10] ;
  assign p1__h52040 = p1__h52054 & p0__h52268 ;
  assign p1__h52054 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[7] &
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[6] ;
  assign p1__h52341 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[3] &
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[2] ;
  assign p1__h8914 = p1__h9979 & p0__h10981 ;
  assign p1__h9979 = p1__h9993 & p0__h10207 ;
  assign p1__h9993 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[23] &
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[22] ;
  assign result___1__h162 =
	     { 1'b1,
	       _0_CONCAT_IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_B_ETC___d900[24] ?
		 { exp_final__h55504,
		   _0_CONCAT_IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_B_ETC___d900[23:1] } :
		 { exp_prenorm__h150,
		   _0_CONCAT_IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_B_ETC___d900[22:0] } } ;
  assign round_bit__h2142 =
	     shift_amt__h509 > 8'd1 &&
	     shifted_out_bits__h2140[i__h16525[4:0]] ;
  assign round_bit__h3821 =
	     shift_amt__h472 > 8'd1 &&
	     shifted_out_bits__h3819[i__h29111[4:0]] ;
  assign shift_amt__h472 =
	     { x__h3604 ^ y__h3605,
	       x__h3415 ^ y__h3416,
	       add_a_BIT_28_8_XOR_INV_add_b_BITS_30_TO_23_2_B_ETC___d138 } ;
  assign shift_amt__h509 =
	     { x__h1945 ^ y__h1946,
	       x__h1756 ^ y__h1757,
	       add_b_BIT_28_1_XOR_INV_add_a_BITS_30_TO_23_5_B_ETC___d71 } ;
  assign shifted_out_bits__h2140 = ma___1__h471 & shifted_out_mask__h2139 ;
  assign shifted_out_bits__h3819 = mb_full__h473 & shifted_out_mask__h3818 ;
  assign shifted_out_mask__h2139 = (24'd1 << shift_amt__h509) - 24'd1 ;
  assign shifted_out_mask__h3818 =
	     { _255_CONCAT_INV_1_SL_add_a_BIT_30_1_XOR_INV_add_ETC__q6[22:0],
	       ~_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335[0] } ;
  assign sticky__h2144 =
	     (shifted_out_bits__h2140 & sticky_mask__h2143) != 24'd0 ;
  assign sticky__h3823 =
	     (shifted_out_bits__h3819 & sticky_mask__h3822) != 24'd0 ;
  assign sticky_mask__h2143 =
	     (shift_amt__h509 <= 8'd2) ?
	       24'd0 :
	       (24'd1 << i__h16525) - 24'd1 ;
  assign sticky_mask__h3822 =
	     (shift_amt__h472 <= 8'd2) ?
	       24'd0 :
	       (24'd1 << i__h29111) - 24'd1 ;
  assign x__h1000 = add_b[25] ^ INV_add_a_BITS_30_TO_23__q1[2] ;
  assign x__h1058 = add_b[24] & INV_add_a_BITS_30_TO_23__q1[1] ;
  assign x__h1189 = add_b[26] ^ INV_add_a_BITS_30_TO_23__q1[3] ;
  assign x__h1247 = add_b[25] & INV_add_a_BITS_30_TO_23__q1[2] ;
  assign x__h1378 = add_b[27] ^ INV_add_a_BITS_30_TO_23__q1[4] ;
  assign x__h1436 = add_b[26] & INV_add_a_BITS_30_TO_23__q1[3] ;
  assign x__h1567 = add_b[28] ^ INV_add_a_BITS_30_TO_23__q1[5] ;
  assign x__h1625 = add_b[27] & INV_add_a_BITS_30_TO_23__q1[4] ;
  assign x__h1756 = add_b[29] ^ INV_add_a_BITS_30_TO_23__q1[6] ;
  assign x__h1814 = add_b[28] & INV_add_a_BITS_30_TO_23__q1[5] ;
  assign x__h1945 = add_b[30] ^ INV_add_a_BITS_30_TO_23__q1[7] ;
  assign x__h2003 = add_b[29] & INV_add_a_BITS_30_TO_23__q1[6] ;
  assign x__h2470 = add_a[24] ^ INV_add_b_BITS_30_TO_23__q2[1] ;
  assign x__h2528 = add_a[23] & INV_add_b_BITS_30_TO_23__q2[0] ;
  assign x__h2659 = add_a[25] ^ INV_add_b_BITS_30_TO_23__q2[2] ;
  assign x__h2717 = add_a[24] & INV_add_b_BITS_30_TO_23__q2[1] ;
  assign x__h28 =
	     (add_a[30:23] != 8'hFF && add_b[30:23] != 8'hFF) ?
	       result___1__h162 :
	       32'h0 ;
  assign x__h2848 = add_a[26] ^ INV_add_b_BITS_30_TO_23__q2[3] ;
  assign x__h2906 = add_a[25] & INV_add_b_BITS_30_TO_23__q2[2] ;
  assign x__h29204 = grs_a___1__h131[1] ^ grs_b___1__h133[1] ;
  assign x__h29390 = grs_a___1__h131[2] ^ grs_b___1__h133[2] ;
  assign x__h29447 = grs_a___1__h131[1] & grs_b___1__h133[1] ;
  assign x__h29633 = grs_a___1__h131[2] & grs_b___1__h133[2] ;
  assign x__h3037 = add_a[27] ^ INV_add_b_BITS_30_TO_23__q2[4] ;
  assign x__h3095 = add_a[26] & INV_add_b_BITS_30_TO_23__q2[3] ;
  assign x__h3226 = add_a[28] ^ INV_add_b_BITS_30_TO_23__q2[5] ;
  assign x__h3284 = add_a[27] & INV_add_b_BITS_30_TO_23__q2[4] ;
  assign x__h3415 = add_a[29] ^ INV_add_b_BITS_30_TO_23__q2[6] ;
  assign x__h3473 = add_a[28] & INV_add_b_BITS_30_TO_23__q2[5] ;
  assign x__h3604 = add_a[30] ^ INV_add_b_BITS_30_TO_23__q2[7] ;
  assign x__h3662 = add_a[29] & INV_add_b_BITS_30_TO_23__q2[6] ;
  assign x__h58759 = add_a[30:23] == 8'hFF || add_b[30:23] == 8'hFF ;
  assign x__h811 = add_b[24] ^ INV_add_a_BITS_30_TO_23__q1[1] ;
  assign x__h869 = add_b[23] & INV_add_a_BITS_30_TO_23__q1[0] ;
  assign y__h10009 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[23] &
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d148[22] ;
  assign y__h1001 = x__h1058 | y__h1059 ;
  assign y__h10135 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[21] &
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d148[20] ;
  assign y__h10282 = p1__h10280 & g0__h10281 ;
  assign y__h10296 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[19] &
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d148[18] ;
  assign y__h10422 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[17] &
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d148[16] ;
  assign y__h1059 = y__h812 & x__h811 ;
  assign y__h1190 = x__h1247 | y__h1248 ;
  assign y__h12135 = p1__h12133 & g0__h12134 ;
  assign y__h12149 = p1__h12147 & g0__h12148 ;
  assign y__h12163 = p1__h12161 & g0__h12162 ;
  assign y__h12177 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[15] &
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d148[14] ;
  assign y__h12303 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[13] &
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d148[12] ;
  assign y__h12450 = p1__h12448 & g0__h12449 ;
  assign y__h12464 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[11] &
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d148[10] ;
  assign y__h1248 = y__h1001 & x__h1000 ;
  assign y__h12590 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[9] &
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d148[8] ;
  assign y__h12758 = p1__h12756 & g0__h12757 ;
  assign y__h12772 = p1__h12770 & g0__h12771 ;
  assign y__h12786 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[7] &
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d148[6] ;
  assign y__h12912 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[5] &
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d148[4] ;
  assign y__h13059 = p1__h13057 & g0__h13058 ;
  assign y__h13073 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[3] &
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d148[2] ;
  assign y__h13199 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[1] &
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d148[0] ;
  assign y__h1379 = x__h1436 | y__h1437 ;
  assign y__h14368 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[22] &
	     g0__h14367 ;
  assign y__h1437 = y__h1190 & x__h1189 ;
  assign y__h14419 = p0__h10207 & g0__h14418 ;
  assign y__h14448 = p0__h10981 & g0__h8915 ;
  assign y__h14559 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[20] &
	     g0__h14418 ;
  assign y__h14692 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[18] &
	     g0__h14691 ;
  assign y__h14743 = p0__h11002 & g0__h8915 ;
  assign y__h14854 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[16] &
	     g0__h8915 ;
  assign y__h14987 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[14] &
	     g0__h14986 ;
  assign y__h15038 = p0__h12375 & g0__h15037 ;
  assign y__h15067 = p0__h12662 & g0__h12134 ;
  assign y__h15207 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[12] &
	     g0__h15037 ;
  assign y__h15340 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[10] &
	     g0__h15339 ;
  assign y__h15391 = p0__h12683 & g0__h12134 ;
  assign y__h15502 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[8] &
	     g0__h12134 ;
  assign y__h15635 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[6] &
	     g0__h15634 ;
  assign y__h1568 = x__h1625 | y__h1626 ;
  assign y__h15686 = p0__h12984 & g0__h12757 ;
  assign y__h15826 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[4] &
	     g0__h12757 ;
  assign y__h15959 =
	     IF_NOT_add_a_BITS_30_TO_23_ULE_add_b_BITS_30_T_ETC___d146[2] &
	     g0__h13058 ;
  assign y__h1626 = y__h1379 & x__h1378 ;
  assign y__h1757 = x__h1814 | y__h1815 ;
  assign y__h1815 = y__h1568 & x__h1567 ;
  assign y__h1946 = x__h2003 | y__h2004 ;
  assign y__h2004 = y__h1757 & x__h1756 ;
  assign y__h21794 = p1__h21792 & g0__h21793 ;
  assign y__h22859 = p1__h22857 & g0__h22858 ;
  assign y__h22873 = p1__h22871 & g0__h22872 ;
  assign y__h22887 =
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[22] &
	     _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335[22] ;
  assign y__h23013 =
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[20] &
	     _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335[20] ;
  assign y__h23160 = p1__h23158 & g0__h23159 ;
  assign y__h23174 =
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[18] &
	     _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335[18] ;
  assign y__h23300 =
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[16] &
	     _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335[16] ;
  assign y__h23954 = p1__h25011 & p0__h26634 ;
  assign y__h2471 = x__h2528 | y__h2529 ;
  assign y__h25013 = p1__h25011 & g0__h25012 ;
  assign y__h25027 = p1__h25025 & g0__h25026 ;
  assign y__h25041 = p1__h25039 & g0__h25040 ;
  assign y__h25055 =
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[14] &
	     _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335[14] ;
  assign y__h25181 =
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[12] &
	     _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335[12] ;
  assign y__h2529 = add_a[23] ^ INV_add_b_BITS_30_TO_23__q2[0] ;
  assign y__h25328 = p1__h25326 & g0__h25327 ;
  assign y__h25342 =
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[10] &
	     _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335[10] ;
  assign y__h25468 =
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[8] &
	     _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335[8] ;
  assign y__h25636 = p1__h25634 & g0__h25635 ;
  assign y__h25650 = p1__h25648 & g0__h25649 ;
  assign y__h25664 =
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[6] &
	     _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335[6] ;
  assign y__h25790 =
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[4] &
	     _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335[4] ;
  assign y__h25937 =
	     p1__h25935 &
	     _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335[1] ;
  assign y__h25951 =
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[2] &
	     _1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30_TO_2_ETC___d335[2] ;
  assign y__h2660 = x__h2717 | y__h2718 ;
  assign y__h27127 = g1__h21791 | y__h21794 ;
  assign y__h2718 = y__h2471 & x__h2470 ;
  assign y__h27260 =
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[21] &
	     g0__h27259 ;
  assign y__h27311 = p0__h23085 & g0__h27310 ;
  assign y__h27340 = p0__h23859 & g0__h21793 ;
  assign y__h27451 =
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[19] &
	     g0__h27310 ;
  assign y__h27584 =
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[17] &
	     g0__h27583 ;
  assign y__h27635 = p0__h23880 & g0__h21793 ;
  assign y__h27746 =
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[15] &
	     g0__h21793 ;
  assign y__h27879 =
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[13] &
	     g0__h27878 ;
  assign y__h27930 = p0__h25253 & g0__h27929 ;
  assign y__h27959 = p0__h25540 & g0__h27958 ;
  assign y__h28099 =
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[11] &
	     g0__h27929 ;
  assign y__h28232 =
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[9] &
	     g0__h28231 ;
  assign y__h28283 = p0__h25561 & g0__h27958 ;
  assign y__h28394 =
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[7] &
	     g0__h27958 ;
  assign y__h2849 = x__h2906 | y__h2907 ;
  assign y__h28527 =
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[5] &
	     g0__h28526 ;
  assign y__h28578 = p0__h25862 & g0__h28577 ;
  assign y__h28718 =
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[3] &
	     g0__h28577 ;
  assign y__h28851 =
	     INV_1_SL_add_a_BIT_30_1_XOR_INV_add_b_BITS_30__ETC__q5[1] &
	     g0__h28850 ;
  assign y__h2907 = y__h2660 & x__h2659 ;
  assign y__h29205 = grs_a___1__h131[0] & grs_b___1__h133[0] ;
  assign y__h29391 = x__h29447 | y__h29448 ;
  assign y__h29448 = y__h29205 & x__h29204 ;
  assign y__h29634 = y__h29391 & x__h29390 ;
  assign y__h3038 = x__h3095 | y__h3096 ;
  assign y__h3096 = y__h2849 & x__h2848 ;
  assign y__h3227 = x__h3284 | y__h3285 ;
  assign y__h3285 = y__h3038 & x__h3037 ;
  assign y__h3416 = x__h3473 | y__h3474 ;
  assign y__h3474 = y__h3227 & x__h3226 ;
  assign y__h35546 = p1__h35544 & g0__h35545 ;
  assign y__h3605 = x__h3662 | y__h3663 ;
  assign y__h36611 = p1__h36609 & g0__h36610 ;
  assign y__h36625 = p1__h36623 & g0__h36624 ;
  assign y__h3663 = y__h3416 & x__h3415 ;
  assign y__h36639 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[23] &
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d549[22] ;
  assign y__h36765 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[21] &
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d549[20] ;
  assign y__h36912 = p1__h36910 & g0__h36911 ;
  assign y__h36926 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[19] &
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d549[18] ;
  assign y__h37052 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[17] &
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d549[16] ;
  assign y__h38765 = p1__h38763 & g0__h38764 ;
  assign y__h38779 = p1__h38777 & g0__h38778 ;
  assign y__h38793 = p1__h38791 & g0__h38792 ;
  assign y__h38807 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[15] &
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d549[14] ;
  assign y__h38933 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[13] &
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d549[12] ;
  assign y__h39080 = p1__h39078 & g0__h39079 ;
  assign y__h39094 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[11] &
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d549[10] ;
  assign y__h39220 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[9] &
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d549[8] ;
  assign y__h39388 = p1__h39386 & g0__h39387 ;
  assign y__h39402 = p1__h39400 & g0__h39401 ;
  assign y__h39416 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[7] &
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d549[6] ;
  assign y__h39542 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[5] &
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d549[4] ;
  assign y__h39689 = p1__h39687 & g0__h39688 ;
  assign y__h39703 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[3] &
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d549[2] ;
  assign y__h39829 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[1] &
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d549[0] ;
  assign y__h40867 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[24] &
	     g0__h40866 ;
  assign y__h41000 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[22] &
	     g0__h40999 ;
  assign y__h41051 = p0__h36837 & g0__h41050 ;
  assign y__h41080 = p0__h37611 & g0__h35545 ;
  assign y__h41191 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[20] &
	     g0__h41050 ;
  assign y__h41324 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[18] &
	     g0__h41323 ;
  assign y__h41375 = p0__h37632 & g0__h35545 ;
  assign y__h41486 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[16] &
	     g0__h35545 ;
  assign y__h41619 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[14] &
	     g0__h41618 ;
  assign y__h41670 = p0__h39005 & g0__h41669 ;
  assign y__h41699 = p0__h39292 & g0__h38764 ;
  assign y__h41839 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[12] &
	     g0__h41669 ;
  assign y__h41972 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[10] &
	     g0__h41971 ;
  assign y__h42023 = p0__h39313 & g0__h38764 ;
  assign y__h42134 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[8] &
	     g0__h38764 ;
  assign y__h42267 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[6] &
	     g0__h42266 ;
  assign y__h42318 = p0__h39614 & g0__h39387 ;
  assign y__h42458 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[4] &
	     g0__h39387 ;
  assign y__h42591 =
	     _0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_23_ULE_add__ETC___d547[2] &
	     g0__h39688 ;
  assign y__h48200 = p1__h48198 & g0__h48199 ;
  assign y__h49265 = p1__h49263 & g0__h49264 ;
  assign y__h49279 = p1__h49277 & g0__h49278 ;
  assign y__h49293 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[23] &
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d739[22] ;
  assign y__h49419 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[21] &
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d739[20] ;
  assign y__h49566 = p1__h49564 & g0__h49565 ;
  assign y__h49580 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[19] &
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d739[18] ;
  assign y__h49706 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[17] &
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d739[16] ;
  assign y__h51419 = p1__h51417 & g0__h51418 ;
  assign y__h51433 = p1__h51431 & g0__h51432 ;
  assign y__h51447 = p1__h51445 & g0__h51446 ;
  assign y__h51461 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[15] &
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d739[14] ;
  assign y__h51587 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[13] &
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d739[12] ;
  assign y__h51734 = p1__h51732 & g0__h51733 ;
  assign y__h51748 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[11] &
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d739[10] ;
  assign y__h51874 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[9] &
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d739[8] ;
  assign y__h52042 = p1__h52040 & g0__h52041 ;
  assign y__h52056 = p1__h52054 & g0__h52055 ;
  assign y__h52070 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[7] &
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d739[6] ;
  assign y__h52196 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[5] &
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d739[4] ;
  assign y__h52343 = p1__h52341 & g0__h52342 ;
  assign y__h52357 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[3] &
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d739[2] ;
  assign y__h52483 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[1] &
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d739[0] ;
  assign y__h53652 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[22] &
	     g0__h53651 ;
  assign y__h53703 = p0__h49491 & g0__h53702 ;
  assign y__h53732 = p0__h50265 & g0__h48199 ;
  assign y__h53843 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[20] &
	     g0__h53702 ;
  assign y__h53976 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[18] &
	     g0__h53975 ;
  assign y__h54027 = p0__h50286 & g0__h48199 ;
  assign y__h54138 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[16] &
	     g0__h48199 ;
  assign y__h54271 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[14] &
	     g0__h54270 ;
  assign y__h54322 = p0__h51659 & g0__h54321 ;
  assign y__h54351 = p0__h51946 & g0__h51418 ;
  assign y__h54491 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[12] &
	     g0__h54321 ;
  assign y__h54624 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[10] &
	     g0__h54623 ;
  assign y__h54675 = p0__h51967 & g0__h51418 ;
  assign y__h54786 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[8] &
	     g0__h51418 ;
  assign y__h54919 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[6] &
	     g0__h54918 ;
  assign y__h54970 = p0__h52268 & g0__h52041 ;
  assign y__h55110 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[4] &
	     g0__h52041 ;
  assign y__h55243 =
	     IF_0_CONCAT_0b0_CONCAT_IF_NOT_add_a_BITS_30_TO_ETC___d737[2] &
	     g0__h52342 ;
  assign y__h56228 = exp_out___1__h134[0] & exp_out___1__h134[1] ;
  assign y__h56417 = y__h56228 & exp_out___1__h134[2] ;
  assign y__h56606 = y__h56417 & exp_out___1__h134[3] ;
  assign y__h56795 = y__h56606 & exp_out___1__h134[4] ;
  assign y__h56984 = y__h56795 & exp_out___1__h134[5] ;
  assign y__h57173 = y__h56984 & exp_out___1__h134[6] ;
  assign y__h57597 = exp_prenorm__h150[0] & exp_prenorm__h150[1] ;
  assign y__h57786 = y__h57597 & exp_prenorm__h150[2] ;
  assign y__h57975 = y__h57786 & exp_prenorm__h150[3] ;
  assign y__h58164 = y__h57975 & exp_prenorm__h150[4] ;
  assign y__h58353 = y__h58164 & exp_prenorm__h150[5] ;
  assign y__h58542 = y__h58353 & exp_prenorm__h150[6] ;
  assign y__h812 = x__h869 | y__h870 ;
  assign y__h870 = add_b[23] ^ INV_add_a_BITS_30_TO_23__q1[0] ;
  assign y__h8916 = p1__h8914 & g0__h8915 ;
  assign y__h9981 = p1__h9979 & g0__h9980 ;
  assign y__h9995 = p1__h9993 & g0__h9994 ;
endmodule  // mkFpAdder

